// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mock

//go:generate minimock -i pvz/internal/usecase/auth.Issuer -o issuer_mock.go -n IssuerMock -p mock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// IssuerMock implements mm_auth.Issuer
type IssuerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcIssue          func(userRole string) (s1 string, err error)
	funcIssueOrigin    string
	inspectFuncIssue   func(userRole string)
	afterIssueCounter  uint64
	beforeIssueCounter uint64
	IssueMock          mIssuerMockIssue
}

// NewIssuerMock returns a mock for mm_auth.Issuer
func NewIssuerMock(t minimock.Tester) *IssuerMock {
	m := &IssuerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.IssueMock = mIssuerMockIssue{mock: m}
	m.IssueMock.callArgs = []*IssuerMockIssueParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mIssuerMockIssue struct {
	optional           bool
	mock               *IssuerMock
	defaultExpectation *IssuerMockIssueExpectation
	expectations       []*IssuerMockIssueExpectation

	callArgs []*IssuerMockIssueParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// IssuerMockIssueExpectation specifies expectation struct of the Issuer.Issue
type IssuerMockIssueExpectation struct {
	mock               *IssuerMock
	params             *IssuerMockIssueParams
	paramPtrs          *IssuerMockIssueParamPtrs
	expectationOrigins IssuerMockIssueExpectationOrigins
	results            *IssuerMockIssueResults
	returnOrigin       string
	Counter            uint64
}

// IssuerMockIssueParams contains parameters of the Issuer.Issue
type IssuerMockIssueParams struct {
	userRole string
}

// IssuerMockIssueParamPtrs contains pointers to parameters of the Issuer.Issue
type IssuerMockIssueParamPtrs struct {
	userRole *string
}

// IssuerMockIssueResults contains results of the Issuer.Issue
type IssuerMockIssueResults struct {
	s1  string
	err error
}

// IssuerMockIssueOrigins contains origins of expectations of the Issuer.Issue
type IssuerMockIssueExpectationOrigins struct {
	origin         string
	originUserRole string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmIssue *mIssuerMockIssue) Optional() *mIssuerMockIssue {
	mmIssue.optional = true
	return mmIssue
}

// Expect sets up expected params for Issuer.Issue
func (mmIssue *mIssuerMockIssue) Expect(userRole string) *mIssuerMockIssue {
	if mmIssue.mock.funcIssue != nil {
		mmIssue.mock.t.Fatalf("IssuerMock.Issue mock is already set by Set")
	}

	if mmIssue.defaultExpectation == nil {
		mmIssue.defaultExpectation = &IssuerMockIssueExpectation{}
	}

	if mmIssue.defaultExpectation.paramPtrs != nil {
		mmIssue.mock.t.Fatalf("IssuerMock.Issue mock is already set by ExpectParams functions")
	}

	mmIssue.defaultExpectation.params = &IssuerMockIssueParams{userRole}
	mmIssue.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmIssue.expectations {
		if minimock.Equal(e.params, mmIssue.defaultExpectation.params) {
			mmIssue.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmIssue.defaultExpectation.params)
		}
	}

	return mmIssue
}

// ExpectUserRoleParam1 sets up expected param userRole for Issuer.Issue
func (mmIssue *mIssuerMockIssue) ExpectUserRoleParam1(userRole string) *mIssuerMockIssue {
	if mmIssue.mock.funcIssue != nil {
		mmIssue.mock.t.Fatalf("IssuerMock.Issue mock is already set by Set")
	}

	if mmIssue.defaultExpectation == nil {
		mmIssue.defaultExpectation = &IssuerMockIssueExpectation{}
	}

	if mmIssue.defaultExpectation.params != nil {
		mmIssue.mock.t.Fatalf("IssuerMock.Issue mock is already set by Expect")
	}

	if mmIssue.defaultExpectation.paramPtrs == nil {
		mmIssue.defaultExpectation.paramPtrs = &IssuerMockIssueParamPtrs{}
	}
	mmIssue.defaultExpectation.paramPtrs.userRole = &userRole
	mmIssue.defaultExpectation.expectationOrigins.originUserRole = minimock.CallerInfo(1)

	return mmIssue
}

// Inspect accepts an inspector function that has same arguments as the Issuer.Issue
func (mmIssue *mIssuerMockIssue) Inspect(f func(userRole string)) *mIssuerMockIssue {
	if mmIssue.mock.inspectFuncIssue != nil {
		mmIssue.mock.t.Fatalf("Inspect function is already set for IssuerMock.Issue")
	}

	mmIssue.mock.inspectFuncIssue = f

	return mmIssue
}

// Return sets up results that will be returned by Issuer.Issue
func (mmIssue *mIssuerMockIssue) Return(s1 string, err error) *IssuerMock {
	if mmIssue.mock.funcIssue != nil {
		mmIssue.mock.t.Fatalf("IssuerMock.Issue mock is already set by Set")
	}

	if mmIssue.defaultExpectation == nil {
		mmIssue.defaultExpectation = &IssuerMockIssueExpectation{mock: mmIssue.mock}
	}
	mmIssue.defaultExpectation.results = &IssuerMockIssueResults{s1, err}
	mmIssue.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmIssue.mock
}

// Set uses given function f to mock the Issuer.Issue method
func (mmIssue *mIssuerMockIssue) Set(f func(userRole string) (s1 string, err error)) *IssuerMock {
	if mmIssue.defaultExpectation != nil {
		mmIssue.mock.t.Fatalf("Default expectation is already set for the Issuer.Issue method")
	}

	if len(mmIssue.expectations) > 0 {
		mmIssue.mock.t.Fatalf("Some expectations are already set for the Issuer.Issue method")
	}

	mmIssue.mock.funcIssue = f
	mmIssue.mock.funcIssueOrigin = minimock.CallerInfo(1)
	return mmIssue.mock
}

// When sets expectation for the Issuer.Issue which will trigger the result defined by the following
// Then helper
func (mmIssue *mIssuerMockIssue) When(userRole string) *IssuerMockIssueExpectation {
	if mmIssue.mock.funcIssue != nil {
		mmIssue.mock.t.Fatalf("IssuerMock.Issue mock is already set by Set")
	}

	expectation := &IssuerMockIssueExpectation{
		mock:               mmIssue.mock,
		params:             &IssuerMockIssueParams{userRole},
		expectationOrigins: IssuerMockIssueExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmIssue.expectations = append(mmIssue.expectations, expectation)
	return expectation
}

// Then sets up Issuer.Issue return parameters for the expectation previously defined by the When method
func (e *IssuerMockIssueExpectation) Then(s1 string, err error) *IssuerMock {
	e.results = &IssuerMockIssueResults{s1, err}
	return e.mock
}

// Times sets number of times Issuer.Issue should be invoked
func (mmIssue *mIssuerMockIssue) Times(n uint64) *mIssuerMockIssue {
	if n == 0 {
		mmIssue.mock.t.Fatalf("Times of IssuerMock.Issue mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmIssue.expectedInvocations, n)
	mmIssue.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmIssue
}

func (mmIssue *mIssuerMockIssue) invocationsDone() bool {
	if len(mmIssue.expectations) == 0 && mmIssue.defaultExpectation == nil && mmIssue.mock.funcIssue == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmIssue.mock.afterIssueCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmIssue.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Issue implements mm_auth.Issuer
func (mmIssue *IssuerMock) Issue(userRole string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmIssue.beforeIssueCounter, 1)
	defer mm_atomic.AddUint64(&mmIssue.afterIssueCounter, 1)

	mmIssue.t.Helper()

	if mmIssue.inspectFuncIssue != nil {
		mmIssue.inspectFuncIssue(userRole)
	}

	mm_params := IssuerMockIssueParams{userRole}

	// Record call args
	mmIssue.IssueMock.mutex.Lock()
	mmIssue.IssueMock.callArgs = append(mmIssue.IssueMock.callArgs, &mm_params)
	mmIssue.IssueMock.mutex.Unlock()

	for _, e := range mmIssue.IssueMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmIssue.IssueMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmIssue.IssueMock.defaultExpectation.Counter, 1)
		mm_want := mmIssue.IssueMock.defaultExpectation.params
		mm_want_ptrs := mmIssue.IssueMock.defaultExpectation.paramPtrs

		mm_got := IssuerMockIssueParams{userRole}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userRole != nil && !minimock.Equal(*mm_want_ptrs.userRole, mm_got.userRole) {
				mmIssue.t.Errorf("IssuerMock.Issue got unexpected parameter userRole, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmIssue.IssueMock.defaultExpectation.expectationOrigins.originUserRole, *mm_want_ptrs.userRole, mm_got.userRole, minimock.Diff(*mm_want_ptrs.userRole, mm_got.userRole))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmIssue.t.Errorf("IssuerMock.Issue got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmIssue.IssueMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmIssue.IssueMock.defaultExpectation.results
		if mm_results == nil {
			mmIssue.t.Fatal("No results are set for the IssuerMock.Issue")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmIssue.funcIssue != nil {
		return mmIssue.funcIssue(userRole)
	}
	mmIssue.t.Fatalf("Unexpected call to IssuerMock.Issue. %v", userRole)
	return
}

// IssueAfterCounter returns a count of finished IssuerMock.Issue invocations
func (mmIssue *IssuerMock) IssueAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIssue.afterIssueCounter)
}

// IssueBeforeCounter returns a count of IssuerMock.Issue invocations
func (mmIssue *IssuerMock) IssueBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIssue.beforeIssueCounter)
}

// Calls returns a list of arguments used in each call to IssuerMock.Issue.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmIssue *mIssuerMockIssue) Calls() []*IssuerMockIssueParams {
	mmIssue.mutex.RLock()

	argCopy := make([]*IssuerMockIssueParams, len(mmIssue.callArgs))
	copy(argCopy, mmIssue.callArgs)

	mmIssue.mutex.RUnlock()

	return argCopy
}

// MinimockIssueDone returns true if the count of the Issue invocations corresponds
// the number of defined expectations
func (m *IssuerMock) MinimockIssueDone() bool {
	if m.IssueMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.IssueMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.IssueMock.invocationsDone()
}

// MinimockIssueInspect logs each unmet expectation
func (m *IssuerMock) MinimockIssueInspect() {
	for _, e := range m.IssueMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IssuerMock.Issue at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterIssueCounter := mm_atomic.LoadUint64(&m.afterIssueCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.IssueMock.defaultExpectation != nil && afterIssueCounter < 1 {
		if m.IssueMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to IssuerMock.Issue at\n%s", m.IssueMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to IssuerMock.Issue at\n%s with params: %#v", m.IssueMock.defaultExpectation.expectationOrigins.origin, *m.IssueMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIssue != nil && afterIssueCounter < 1 {
		m.t.Errorf("Expected call to IssuerMock.Issue at\n%s", m.funcIssueOrigin)
	}

	if !m.IssueMock.invocationsDone() && afterIssueCounter > 0 {
		m.t.Errorf("Expected %d calls to IssuerMock.Issue at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.IssueMock.expectedInvocations), m.IssueMock.expectedInvocationsOrigin, afterIssueCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IssuerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockIssueInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IssuerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IssuerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockIssueDone()
}
