syntax = "proto3";

package pvz.v1;

option go_package = "github.com/BlankBot-0/pvz/pvz_v1;pvz_v1";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";
import "google/api/field_behavior.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

service PVZService {
  rpc ListPVZ(ListPVZRequest) returns (ListPVZResponse) {
    option (google.api.http) = {
      get: "/pvz",
      response_body: "pvzs"
    };
  };
  rpc CreatePVZ(CreatePVZRequest) returns (CreatePVZResponse) {
    option (google.api.http) = {
      post: "/pvz",
      response_body: "pvz"
    };
  };

  rpc CreateReception(CreateReceptionRequest) returns (CreateReceptionResponse) {
    option (google.api.http) = {
      post: "/receptions",
      response_body: "reception"
    };
  };
  rpc CloseLastReception(CloseLastReceptionRequest) returns (CloseLastReceptionResponse) {
    option (google.api.http) = {
      post: "/pvz/{pvzId}/close_last_reception",
      response_body: "reception"
    };
  };
  rpc CreateProduct(CreateProductRequest) returns (CreateProductResponse) {
    option (google.api.http) = {
      post: "/products",
      response_body: "product"
    };
  };
  rpc DeleteLastProduct(DeleteLastProductRequest) returns (DeleteLastProductResponse) {
    option (google.api.http) = {
      post: "/pvz/{pvzId}/delete_last_product"
    };
  };

  rpc DummyLogin(DummyLoginRequest) returns (DummyLoginResponse) {
    option (google.api.http) = {
      post: "/dummyLogin",
      response_body: "token"
    };
  };
  rpc Register(RegisterRequest) returns (RegisterResponse) {
    option (google.api.http) = {
      post: "/register"
    };
  };
  rpc Login(LoginRequest) returns (LoginResponse) {
    option (google.api.http) = {
      post: "/login",
      response_body: "token"
    };
  };

  rpc GetPVZList(google.protobuf.Empty) returns (GetPVZListResponse);
}

message ListPVZRequest {
  google.protobuf.Timestamp start_date = 1;
  google.protobuf.Timestamp end_date = 2;
  uint32 page = 3;
  uint32 limit = 4;
}

message ListPVZResponse {
  message receptionInfo {
    Reception reception = 1;
    repeated Product products = 2;
  }
  message pvzInfo {
    PVZ pvz = 1;
    repeated receptionInfo receptions = 2;
  }

  repeated pvzInfo pvzs = 1;
}

message CreatePVZRequest {
  string city = 1;
}

message CreatePVZResponse {
  PVZ pvz = 1;
}

message CreateReceptionRequest {
  string pvzId = 1;
}

message CreateReceptionResponse {
  Reception reception = 1;
}

message CloseLastReceptionRequest {
  string pvzId = 1;
}

message CloseLastReceptionResponse {
  Reception reception = 1;
}

message CreateProductRequest {
  string type = 1;
  string pvzId = 2;
}

message CreateProductResponse {
  Product product = 1;
}

message DeleteLastProductRequest {
  string pvzId = 1;
}

message DeleteLastProductResponse {
  string message = 1;
}

message DummyLoginRequest {
  string role = 1;
}

message DummyLoginResponse {
  string token = 1;
}

message RegisterRequest {
  string email = 1;
  string password = 2;
  string role = 3;
}

message RegisterResponse {
  string id = 1;
  string email = 2;
  string role = 3;
}

message LoginRequest {
  string email = 1 [(validate.rules).string = {email: true}];
  string password = 2;
}

message LoginResponse {
  string token = 1;
}

message GetPVZListResponse {
  repeated PVZ pvzs = 1;
}

message PVZ {
  string id = 1;
  google.protobuf.Timestamp registration_date = 2;
  string city = 3;
}

message Reception {
  string id = 1;
  google.protobuf.Timestamp date_time = 2;
  string pvz_id = 3;
  string status = 4;
}

message Product {
  string id = 1;
  google.protobuf.Timestamp date_time = 2;
  string type = 3;
  string reception_id = 4;
}