// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i pvz/internal/app/grpc.AuthService -o auth_mock.go -n AuthMock -p mocks

import (
	"context"
	"pvz/internal/models"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AuthMock implements mm_pvz.AuthService
type AuthMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDummyLogin          func(ctx context.Context, role string) (s1 string, err error)
	funcDummyLoginOrigin    string
	inspectFuncDummyLogin   func(ctx context.Context, role string)
	afterDummyLoginCounter  uint64
	beforeDummyLoginCounter uint64
	DummyLoginMock          mAuthMockDummyLogin

	funcRegister          func(ctx context.Context, email string, password string, role string) (u1 models.User, err error)
	funcRegisterOrigin    string
	inspectFuncRegister   func(ctx context.Context, email string, password string, role string)
	afterRegisterCounter  uint64
	beforeRegisterCounter uint64
	RegisterMock          mAuthMockRegister

	funcUserToken          func(ctx context.Context, email string, password string) (s1 string, err error)
	funcUserTokenOrigin    string
	inspectFuncUserToken   func(ctx context.Context, email string, password string)
	afterUserTokenCounter  uint64
	beforeUserTokenCounter uint64
	UserTokenMock          mAuthMockUserToken
}

// NewAuthMock returns a mock for mm_pvz.AuthService
func NewAuthMock(t minimock.Tester) *AuthMock {
	m := &AuthMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DummyLoginMock = mAuthMockDummyLogin{mock: m}
	m.DummyLoginMock.callArgs = []*AuthMockDummyLoginParams{}

	m.RegisterMock = mAuthMockRegister{mock: m}
	m.RegisterMock.callArgs = []*AuthMockRegisterParams{}

	m.UserTokenMock = mAuthMockUserToken{mock: m}
	m.UserTokenMock.callArgs = []*AuthMockUserTokenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuthMockDummyLogin struct {
	optional           bool
	mock               *AuthMock
	defaultExpectation *AuthMockDummyLoginExpectation
	expectations       []*AuthMockDummyLoginExpectation

	callArgs []*AuthMockDummyLoginParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthMockDummyLoginExpectation specifies expectation struct of the AuthService.DummyLogin
type AuthMockDummyLoginExpectation struct {
	mock               *AuthMock
	params             *AuthMockDummyLoginParams
	paramPtrs          *AuthMockDummyLoginParamPtrs
	expectationOrigins AuthMockDummyLoginExpectationOrigins
	results            *AuthMockDummyLoginResults
	returnOrigin       string
	Counter            uint64
}

// AuthMockDummyLoginParams contains parameters of the AuthService.DummyLogin
type AuthMockDummyLoginParams struct {
	ctx  context.Context
	role string
}

// AuthMockDummyLoginParamPtrs contains pointers to parameters of the AuthService.DummyLogin
type AuthMockDummyLoginParamPtrs struct {
	ctx  *context.Context
	role *string
}

// AuthMockDummyLoginResults contains results of the AuthService.DummyLogin
type AuthMockDummyLoginResults struct {
	s1  string
	err error
}

// AuthMockDummyLoginOrigins contains origins of expectations of the AuthService.DummyLogin
type AuthMockDummyLoginExpectationOrigins struct {
	origin     string
	originCtx  string
	originRole string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDummyLogin *mAuthMockDummyLogin) Optional() *mAuthMockDummyLogin {
	mmDummyLogin.optional = true
	return mmDummyLogin
}

// Expect sets up expected params for AuthService.DummyLogin
func (mmDummyLogin *mAuthMockDummyLogin) Expect(ctx context.Context, role string) *mAuthMockDummyLogin {
	if mmDummyLogin.mock.funcDummyLogin != nil {
		mmDummyLogin.mock.t.Fatalf("AuthMock.DummyLogin mock is already set by Set")
	}

	if mmDummyLogin.defaultExpectation == nil {
		mmDummyLogin.defaultExpectation = &AuthMockDummyLoginExpectation{}
	}

	if mmDummyLogin.defaultExpectation.paramPtrs != nil {
		mmDummyLogin.mock.t.Fatalf("AuthMock.DummyLogin mock is already set by ExpectParams functions")
	}

	mmDummyLogin.defaultExpectation.params = &AuthMockDummyLoginParams{ctx, role}
	mmDummyLogin.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDummyLogin.expectations {
		if minimock.Equal(e.params, mmDummyLogin.defaultExpectation.params) {
			mmDummyLogin.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDummyLogin.defaultExpectation.params)
		}
	}

	return mmDummyLogin
}

// ExpectCtxParam1 sets up expected param ctx for AuthService.DummyLogin
func (mmDummyLogin *mAuthMockDummyLogin) ExpectCtxParam1(ctx context.Context) *mAuthMockDummyLogin {
	if mmDummyLogin.mock.funcDummyLogin != nil {
		mmDummyLogin.mock.t.Fatalf("AuthMock.DummyLogin mock is already set by Set")
	}

	if mmDummyLogin.defaultExpectation == nil {
		mmDummyLogin.defaultExpectation = &AuthMockDummyLoginExpectation{}
	}

	if mmDummyLogin.defaultExpectation.params != nil {
		mmDummyLogin.mock.t.Fatalf("AuthMock.DummyLogin mock is already set by Expect")
	}

	if mmDummyLogin.defaultExpectation.paramPtrs == nil {
		mmDummyLogin.defaultExpectation.paramPtrs = &AuthMockDummyLoginParamPtrs{}
	}
	mmDummyLogin.defaultExpectation.paramPtrs.ctx = &ctx
	mmDummyLogin.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDummyLogin
}

// ExpectRoleParam2 sets up expected param role for AuthService.DummyLogin
func (mmDummyLogin *mAuthMockDummyLogin) ExpectRoleParam2(role string) *mAuthMockDummyLogin {
	if mmDummyLogin.mock.funcDummyLogin != nil {
		mmDummyLogin.mock.t.Fatalf("AuthMock.DummyLogin mock is already set by Set")
	}

	if mmDummyLogin.defaultExpectation == nil {
		mmDummyLogin.defaultExpectation = &AuthMockDummyLoginExpectation{}
	}

	if mmDummyLogin.defaultExpectation.params != nil {
		mmDummyLogin.mock.t.Fatalf("AuthMock.DummyLogin mock is already set by Expect")
	}

	if mmDummyLogin.defaultExpectation.paramPtrs == nil {
		mmDummyLogin.defaultExpectation.paramPtrs = &AuthMockDummyLoginParamPtrs{}
	}
	mmDummyLogin.defaultExpectation.paramPtrs.role = &role
	mmDummyLogin.defaultExpectation.expectationOrigins.originRole = minimock.CallerInfo(1)

	return mmDummyLogin
}

// Inspect accepts an inspector function that has same arguments as the AuthService.DummyLogin
func (mmDummyLogin *mAuthMockDummyLogin) Inspect(f func(ctx context.Context, role string)) *mAuthMockDummyLogin {
	if mmDummyLogin.mock.inspectFuncDummyLogin != nil {
		mmDummyLogin.mock.t.Fatalf("Inspect function is already set for AuthMock.DummyLogin")
	}

	mmDummyLogin.mock.inspectFuncDummyLogin = f

	return mmDummyLogin
}

// Return sets up results that will be returned by AuthService.DummyLogin
func (mmDummyLogin *mAuthMockDummyLogin) Return(s1 string, err error) *AuthMock {
	if mmDummyLogin.mock.funcDummyLogin != nil {
		mmDummyLogin.mock.t.Fatalf("AuthMock.DummyLogin mock is already set by Set")
	}

	if mmDummyLogin.defaultExpectation == nil {
		mmDummyLogin.defaultExpectation = &AuthMockDummyLoginExpectation{mock: mmDummyLogin.mock}
	}
	mmDummyLogin.defaultExpectation.results = &AuthMockDummyLoginResults{s1, err}
	mmDummyLogin.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDummyLogin.mock
}

// Set uses given function f to mock the AuthService.DummyLogin method
func (mmDummyLogin *mAuthMockDummyLogin) Set(f func(ctx context.Context, role string) (s1 string, err error)) *AuthMock {
	if mmDummyLogin.defaultExpectation != nil {
		mmDummyLogin.mock.t.Fatalf("Default expectation is already set for the AuthService.DummyLogin method")
	}

	if len(mmDummyLogin.expectations) > 0 {
		mmDummyLogin.mock.t.Fatalf("Some expectations are already set for the AuthService.DummyLogin method")
	}

	mmDummyLogin.mock.funcDummyLogin = f
	mmDummyLogin.mock.funcDummyLoginOrigin = minimock.CallerInfo(1)
	return mmDummyLogin.mock
}

// When sets expectation for the AuthService.DummyLogin which will trigger the result defined by the following
// Then helper
func (mmDummyLogin *mAuthMockDummyLogin) When(ctx context.Context, role string) *AuthMockDummyLoginExpectation {
	if mmDummyLogin.mock.funcDummyLogin != nil {
		mmDummyLogin.mock.t.Fatalf("AuthMock.DummyLogin mock is already set by Set")
	}

	expectation := &AuthMockDummyLoginExpectation{
		mock:               mmDummyLogin.mock,
		params:             &AuthMockDummyLoginParams{ctx, role},
		expectationOrigins: AuthMockDummyLoginExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDummyLogin.expectations = append(mmDummyLogin.expectations, expectation)
	return expectation
}

// Then sets up AuthService.DummyLogin return parameters for the expectation previously defined by the When method
func (e *AuthMockDummyLoginExpectation) Then(s1 string, err error) *AuthMock {
	e.results = &AuthMockDummyLoginResults{s1, err}
	return e.mock
}

// Times sets number of times AuthService.DummyLogin should be invoked
func (mmDummyLogin *mAuthMockDummyLogin) Times(n uint64) *mAuthMockDummyLogin {
	if n == 0 {
		mmDummyLogin.mock.t.Fatalf("Times of AuthMock.DummyLogin mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDummyLogin.expectedInvocations, n)
	mmDummyLogin.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDummyLogin
}

func (mmDummyLogin *mAuthMockDummyLogin) invocationsDone() bool {
	if len(mmDummyLogin.expectations) == 0 && mmDummyLogin.defaultExpectation == nil && mmDummyLogin.mock.funcDummyLogin == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDummyLogin.mock.afterDummyLoginCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDummyLogin.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DummyLogin implements mm_pvz.AuthService
func (mmDummyLogin *AuthMock) DummyLogin(ctx context.Context, role string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmDummyLogin.beforeDummyLoginCounter, 1)
	defer mm_atomic.AddUint64(&mmDummyLogin.afterDummyLoginCounter, 1)

	mmDummyLogin.t.Helper()

	if mmDummyLogin.inspectFuncDummyLogin != nil {
		mmDummyLogin.inspectFuncDummyLogin(ctx, role)
	}

	mm_params := AuthMockDummyLoginParams{ctx, role}

	// Record call args
	mmDummyLogin.DummyLoginMock.mutex.Lock()
	mmDummyLogin.DummyLoginMock.callArgs = append(mmDummyLogin.DummyLoginMock.callArgs, &mm_params)
	mmDummyLogin.DummyLoginMock.mutex.Unlock()

	for _, e := range mmDummyLogin.DummyLoginMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmDummyLogin.DummyLoginMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDummyLogin.DummyLoginMock.defaultExpectation.Counter, 1)
		mm_want := mmDummyLogin.DummyLoginMock.defaultExpectation.params
		mm_want_ptrs := mmDummyLogin.DummyLoginMock.defaultExpectation.paramPtrs

		mm_got := AuthMockDummyLoginParams{ctx, role}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDummyLogin.t.Errorf("AuthMock.DummyLogin got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDummyLogin.DummyLoginMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.role != nil && !minimock.Equal(*mm_want_ptrs.role, mm_got.role) {
				mmDummyLogin.t.Errorf("AuthMock.DummyLogin got unexpected parameter role, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDummyLogin.DummyLoginMock.defaultExpectation.expectationOrigins.originRole, *mm_want_ptrs.role, mm_got.role, minimock.Diff(*mm_want_ptrs.role, mm_got.role))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDummyLogin.t.Errorf("AuthMock.DummyLogin got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDummyLogin.DummyLoginMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDummyLogin.DummyLoginMock.defaultExpectation.results
		if mm_results == nil {
			mmDummyLogin.t.Fatal("No results are set for the AuthMock.DummyLogin")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmDummyLogin.funcDummyLogin != nil {
		return mmDummyLogin.funcDummyLogin(ctx, role)
	}
	mmDummyLogin.t.Fatalf("Unexpected call to AuthMock.DummyLogin. %v %v", ctx, role)
	return
}

// DummyLoginAfterCounter returns a count of finished AuthMock.DummyLogin invocations
func (mmDummyLogin *AuthMock) DummyLoginAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDummyLogin.afterDummyLoginCounter)
}

// DummyLoginBeforeCounter returns a count of AuthMock.DummyLogin invocations
func (mmDummyLogin *AuthMock) DummyLoginBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDummyLogin.beforeDummyLoginCounter)
}

// Calls returns a list of arguments used in each call to AuthMock.DummyLogin.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDummyLogin *mAuthMockDummyLogin) Calls() []*AuthMockDummyLoginParams {
	mmDummyLogin.mutex.RLock()

	argCopy := make([]*AuthMockDummyLoginParams, len(mmDummyLogin.callArgs))
	copy(argCopy, mmDummyLogin.callArgs)

	mmDummyLogin.mutex.RUnlock()

	return argCopy
}

// MinimockDummyLoginDone returns true if the count of the DummyLogin invocations corresponds
// the number of defined expectations
func (m *AuthMock) MinimockDummyLoginDone() bool {
	if m.DummyLoginMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DummyLoginMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DummyLoginMock.invocationsDone()
}

// MinimockDummyLoginInspect logs each unmet expectation
func (m *AuthMock) MinimockDummyLoginInspect() {
	for _, e := range m.DummyLoginMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthMock.DummyLogin at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDummyLoginCounter := mm_atomic.LoadUint64(&m.afterDummyLoginCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DummyLoginMock.defaultExpectation != nil && afterDummyLoginCounter < 1 {
		if m.DummyLoginMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthMock.DummyLogin at\n%s", m.DummyLoginMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthMock.DummyLogin at\n%s with params: %#v", m.DummyLoginMock.defaultExpectation.expectationOrigins.origin, *m.DummyLoginMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDummyLogin != nil && afterDummyLoginCounter < 1 {
		m.t.Errorf("Expected call to AuthMock.DummyLogin at\n%s", m.funcDummyLoginOrigin)
	}

	if !m.DummyLoginMock.invocationsDone() && afterDummyLoginCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthMock.DummyLogin at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DummyLoginMock.expectedInvocations), m.DummyLoginMock.expectedInvocationsOrigin, afterDummyLoginCounter)
	}
}

type mAuthMockRegister struct {
	optional           bool
	mock               *AuthMock
	defaultExpectation *AuthMockRegisterExpectation
	expectations       []*AuthMockRegisterExpectation

	callArgs []*AuthMockRegisterParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthMockRegisterExpectation specifies expectation struct of the AuthService.Register
type AuthMockRegisterExpectation struct {
	mock               *AuthMock
	params             *AuthMockRegisterParams
	paramPtrs          *AuthMockRegisterParamPtrs
	expectationOrigins AuthMockRegisterExpectationOrigins
	results            *AuthMockRegisterResults
	returnOrigin       string
	Counter            uint64
}

// AuthMockRegisterParams contains parameters of the AuthService.Register
type AuthMockRegisterParams struct {
	ctx      context.Context
	email    string
	password string
	role     string
}

// AuthMockRegisterParamPtrs contains pointers to parameters of the AuthService.Register
type AuthMockRegisterParamPtrs struct {
	ctx      *context.Context
	email    *string
	password *string
	role     *string
}

// AuthMockRegisterResults contains results of the AuthService.Register
type AuthMockRegisterResults struct {
	u1  models.User
	err error
}

// AuthMockRegisterOrigins contains origins of expectations of the AuthService.Register
type AuthMockRegisterExpectationOrigins struct {
	origin         string
	originCtx      string
	originEmail    string
	originPassword string
	originRole     string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRegister *mAuthMockRegister) Optional() *mAuthMockRegister {
	mmRegister.optional = true
	return mmRegister
}

// Expect sets up expected params for AuthService.Register
func (mmRegister *mAuthMockRegister) Expect(ctx context.Context, email string, password string, role string) *mAuthMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &AuthMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.paramPtrs != nil {
		mmRegister.mock.t.Fatalf("AuthMock.Register mock is already set by ExpectParams functions")
	}

	mmRegister.defaultExpectation.params = &AuthMockRegisterParams{ctx, email, password, role}
	mmRegister.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRegister.expectations {
		if minimock.Equal(e.params, mmRegister.defaultExpectation.params) {
			mmRegister.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRegister.defaultExpectation.params)
		}
	}

	return mmRegister
}

// ExpectCtxParam1 sets up expected param ctx for AuthService.Register
func (mmRegister *mAuthMockRegister) ExpectCtxParam1(ctx context.Context) *mAuthMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &AuthMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.params != nil {
		mmRegister.mock.t.Fatalf("AuthMock.Register mock is already set by Expect")
	}

	if mmRegister.defaultExpectation.paramPtrs == nil {
		mmRegister.defaultExpectation.paramPtrs = &AuthMockRegisterParamPtrs{}
	}
	mmRegister.defaultExpectation.paramPtrs.ctx = &ctx
	mmRegister.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRegister
}

// ExpectEmailParam2 sets up expected param email for AuthService.Register
func (mmRegister *mAuthMockRegister) ExpectEmailParam2(email string) *mAuthMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &AuthMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.params != nil {
		mmRegister.mock.t.Fatalf("AuthMock.Register mock is already set by Expect")
	}

	if mmRegister.defaultExpectation.paramPtrs == nil {
		mmRegister.defaultExpectation.paramPtrs = &AuthMockRegisterParamPtrs{}
	}
	mmRegister.defaultExpectation.paramPtrs.email = &email
	mmRegister.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmRegister
}

// ExpectPasswordParam3 sets up expected param password for AuthService.Register
func (mmRegister *mAuthMockRegister) ExpectPasswordParam3(password string) *mAuthMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &AuthMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.params != nil {
		mmRegister.mock.t.Fatalf("AuthMock.Register mock is already set by Expect")
	}

	if mmRegister.defaultExpectation.paramPtrs == nil {
		mmRegister.defaultExpectation.paramPtrs = &AuthMockRegisterParamPtrs{}
	}
	mmRegister.defaultExpectation.paramPtrs.password = &password
	mmRegister.defaultExpectation.expectationOrigins.originPassword = minimock.CallerInfo(1)

	return mmRegister
}

// ExpectRoleParam4 sets up expected param role for AuthService.Register
func (mmRegister *mAuthMockRegister) ExpectRoleParam4(role string) *mAuthMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &AuthMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.params != nil {
		mmRegister.mock.t.Fatalf("AuthMock.Register mock is already set by Expect")
	}

	if mmRegister.defaultExpectation.paramPtrs == nil {
		mmRegister.defaultExpectation.paramPtrs = &AuthMockRegisterParamPtrs{}
	}
	mmRegister.defaultExpectation.paramPtrs.role = &role
	mmRegister.defaultExpectation.expectationOrigins.originRole = minimock.CallerInfo(1)

	return mmRegister
}

// Inspect accepts an inspector function that has same arguments as the AuthService.Register
func (mmRegister *mAuthMockRegister) Inspect(f func(ctx context.Context, email string, password string, role string)) *mAuthMockRegister {
	if mmRegister.mock.inspectFuncRegister != nil {
		mmRegister.mock.t.Fatalf("Inspect function is already set for AuthMock.Register")
	}

	mmRegister.mock.inspectFuncRegister = f

	return mmRegister
}

// Return sets up results that will be returned by AuthService.Register
func (mmRegister *mAuthMockRegister) Return(u1 models.User, err error) *AuthMock {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &AuthMockRegisterExpectation{mock: mmRegister.mock}
	}
	mmRegister.defaultExpectation.results = &AuthMockRegisterResults{u1, err}
	mmRegister.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRegister.mock
}

// Set uses given function f to mock the AuthService.Register method
func (mmRegister *mAuthMockRegister) Set(f func(ctx context.Context, email string, password string, role string) (u1 models.User, err error)) *AuthMock {
	if mmRegister.defaultExpectation != nil {
		mmRegister.mock.t.Fatalf("Default expectation is already set for the AuthService.Register method")
	}

	if len(mmRegister.expectations) > 0 {
		mmRegister.mock.t.Fatalf("Some expectations are already set for the AuthService.Register method")
	}

	mmRegister.mock.funcRegister = f
	mmRegister.mock.funcRegisterOrigin = minimock.CallerInfo(1)
	return mmRegister.mock
}

// When sets expectation for the AuthService.Register which will trigger the result defined by the following
// Then helper
func (mmRegister *mAuthMockRegister) When(ctx context.Context, email string, password string, role string) *AuthMockRegisterExpectation {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthMock.Register mock is already set by Set")
	}

	expectation := &AuthMockRegisterExpectation{
		mock:               mmRegister.mock,
		params:             &AuthMockRegisterParams{ctx, email, password, role},
		expectationOrigins: AuthMockRegisterExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRegister.expectations = append(mmRegister.expectations, expectation)
	return expectation
}

// Then sets up AuthService.Register return parameters for the expectation previously defined by the When method
func (e *AuthMockRegisterExpectation) Then(u1 models.User, err error) *AuthMock {
	e.results = &AuthMockRegisterResults{u1, err}
	return e.mock
}

// Times sets number of times AuthService.Register should be invoked
func (mmRegister *mAuthMockRegister) Times(n uint64) *mAuthMockRegister {
	if n == 0 {
		mmRegister.mock.t.Fatalf("Times of AuthMock.Register mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRegister.expectedInvocations, n)
	mmRegister.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRegister
}

func (mmRegister *mAuthMockRegister) invocationsDone() bool {
	if len(mmRegister.expectations) == 0 && mmRegister.defaultExpectation == nil && mmRegister.mock.funcRegister == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRegister.mock.afterRegisterCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRegister.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Register implements mm_pvz.AuthService
func (mmRegister *AuthMock) Register(ctx context.Context, email string, password string, role string) (u1 models.User, err error) {
	mm_atomic.AddUint64(&mmRegister.beforeRegisterCounter, 1)
	defer mm_atomic.AddUint64(&mmRegister.afterRegisterCounter, 1)

	mmRegister.t.Helper()

	if mmRegister.inspectFuncRegister != nil {
		mmRegister.inspectFuncRegister(ctx, email, password, role)
	}

	mm_params := AuthMockRegisterParams{ctx, email, password, role}

	// Record call args
	mmRegister.RegisterMock.mutex.Lock()
	mmRegister.RegisterMock.callArgs = append(mmRegister.RegisterMock.callArgs, &mm_params)
	mmRegister.RegisterMock.mutex.Unlock()

	for _, e := range mmRegister.RegisterMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmRegister.RegisterMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRegister.RegisterMock.defaultExpectation.Counter, 1)
		mm_want := mmRegister.RegisterMock.defaultExpectation.params
		mm_want_ptrs := mmRegister.RegisterMock.defaultExpectation.paramPtrs

		mm_got := AuthMockRegisterParams{ctx, email, password, role}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRegister.t.Errorf("AuthMock.Register got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegister.RegisterMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmRegister.t.Errorf("AuthMock.Register got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegister.RegisterMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

			if mm_want_ptrs.password != nil && !minimock.Equal(*mm_want_ptrs.password, mm_got.password) {
				mmRegister.t.Errorf("AuthMock.Register got unexpected parameter password, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegister.RegisterMock.defaultExpectation.expectationOrigins.originPassword, *mm_want_ptrs.password, mm_got.password, minimock.Diff(*mm_want_ptrs.password, mm_got.password))
			}

			if mm_want_ptrs.role != nil && !minimock.Equal(*mm_want_ptrs.role, mm_got.role) {
				mmRegister.t.Errorf("AuthMock.Register got unexpected parameter role, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegister.RegisterMock.defaultExpectation.expectationOrigins.originRole, *mm_want_ptrs.role, mm_got.role, minimock.Diff(*mm_want_ptrs.role, mm_got.role))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRegister.t.Errorf("AuthMock.Register got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRegister.RegisterMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRegister.RegisterMock.defaultExpectation.results
		if mm_results == nil {
			mmRegister.t.Fatal("No results are set for the AuthMock.Register")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmRegister.funcRegister != nil {
		return mmRegister.funcRegister(ctx, email, password, role)
	}
	mmRegister.t.Fatalf("Unexpected call to AuthMock.Register. %v %v %v %v", ctx, email, password, role)
	return
}

// RegisterAfterCounter returns a count of finished AuthMock.Register invocations
func (mmRegister *AuthMock) RegisterAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRegister.afterRegisterCounter)
}

// RegisterBeforeCounter returns a count of AuthMock.Register invocations
func (mmRegister *AuthMock) RegisterBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRegister.beforeRegisterCounter)
}

// Calls returns a list of arguments used in each call to AuthMock.Register.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRegister *mAuthMockRegister) Calls() []*AuthMockRegisterParams {
	mmRegister.mutex.RLock()

	argCopy := make([]*AuthMockRegisterParams, len(mmRegister.callArgs))
	copy(argCopy, mmRegister.callArgs)

	mmRegister.mutex.RUnlock()

	return argCopy
}

// MinimockRegisterDone returns true if the count of the Register invocations corresponds
// the number of defined expectations
func (m *AuthMock) MinimockRegisterDone() bool {
	if m.RegisterMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RegisterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RegisterMock.invocationsDone()
}

// MinimockRegisterInspect logs each unmet expectation
func (m *AuthMock) MinimockRegisterInspect() {
	for _, e := range m.RegisterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthMock.Register at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRegisterCounter := mm_atomic.LoadUint64(&m.afterRegisterCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RegisterMock.defaultExpectation != nil && afterRegisterCounter < 1 {
		if m.RegisterMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthMock.Register at\n%s", m.RegisterMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthMock.Register at\n%s with params: %#v", m.RegisterMock.defaultExpectation.expectationOrigins.origin, *m.RegisterMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRegister != nil && afterRegisterCounter < 1 {
		m.t.Errorf("Expected call to AuthMock.Register at\n%s", m.funcRegisterOrigin)
	}

	if !m.RegisterMock.invocationsDone() && afterRegisterCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthMock.Register at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RegisterMock.expectedInvocations), m.RegisterMock.expectedInvocationsOrigin, afterRegisterCounter)
	}
}

type mAuthMockUserToken struct {
	optional           bool
	mock               *AuthMock
	defaultExpectation *AuthMockUserTokenExpectation
	expectations       []*AuthMockUserTokenExpectation

	callArgs []*AuthMockUserTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthMockUserTokenExpectation specifies expectation struct of the AuthService.UserToken
type AuthMockUserTokenExpectation struct {
	mock               *AuthMock
	params             *AuthMockUserTokenParams
	paramPtrs          *AuthMockUserTokenParamPtrs
	expectationOrigins AuthMockUserTokenExpectationOrigins
	results            *AuthMockUserTokenResults
	returnOrigin       string
	Counter            uint64
}

// AuthMockUserTokenParams contains parameters of the AuthService.UserToken
type AuthMockUserTokenParams struct {
	ctx      context.Context
	email    string
	password string
}

// AuthMockUserTokenParamPtrs contains pointers to parameters of the AuthService.UserToken
type AuthMockUserTokenParamPtrs struct {
	ctx      *context.Context
	email    *string
	password *string
}

// AuthMockUserTokenResults contains results of the AuthService.UserToken
type AuthMockUserTokenResults struct {
	s1  string
	err error
}

// AuthMockUserTokenOrigins contains origins of expectations of the AuthService.UserToken
type AuthMockUserTokenExpectationOrigins struct {
	origin         string
	originCtx      string
	originEmail    string
	originPassword string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUserToken *mAuthMockUserToken) Optional() *mAuthMockUserToken {
	mmUserToken.optional = true
	return mmUserToken
}

// Expect sets up expected params for AuthService.UserToken
func (mmUserToken *mAuthMockUserToken) Expect(ctx context.Context, email string, password string) *mAuthMockUserToken {
	if mmUserToken.mock.funcUserToken != nil {
		mmUserToken.mock.t.Fatalf("AuthMock.UserToken mock is already set by Set")
	}

	if mmUserToken.defaultExpectation == nil {
		mmUserToken.defaultExpectation = &AuthMockUserTokenExpectation{}
	}

	if mmUserToken.defaultExpectation.paramPtrs != nil {
		mmUserToken.mock.t.Fatalf("AuthMock.UserToken mock is already set by ExpectParams functions")
	}

	mmUserToken.defaultExpectation.params = &AuthMockUserTokenParams{ctx, email, password}
	mmUserToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUserToken.expectations {
		if minimock.Equal(e.params, mmUserToken.defaultExpectation.params) {
			mmUserToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUserToken.defaultExpectation.params)
		}
	}

	return mmUserToken
}

// ExpectCtxParam1 sets up expected param ctx for AuthService.UserToken
func (mmUserToken *mAuthMockUserToken) ExpectCtxParam1(ctx context.Context) *mAuthMockUserToken {
	if mmUserToken.mock.funcUserToken != nil {
		mmUserToken.mock.t.Fatalf("AuthMock.UserToken mock is already set by Set")
	}

	if mmUserToken.defaultExpectation == nil {
		mmUserToken.defaultExpectation = &AuthMockUserTokenExpectation{}
	}

	if mmUserToken.defaultExpectation.params != nil {
		mmUserToken.mock.t.Fatalf("AuthMock.UserToken mock is already set by Expect")
	}

	if mmUserToken.defaultExpectation.paramPtrs == nil {
		mmUserToken.defaultExpectation.paramPtrs = &AuthMockUserTokenParamPtrs{}
	}
	mmUserToken.defaultExpectation.paramPtrs.ctx = &ctx
	mmUserToken.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUserToken
}

// ExpectEmailParam2 sets up expected param email for AuthService.UserToken
func (mmUserToken *mAuthMockUserToken) ExpectEmailParam2(email string) *mAuthMockUserToken {
	if mmUserToken.mock.funcUserToken != nil {
		mmUserToken.mock.t.Fatalf("AuthMock.UserToken mock is already set by Set")
	}

	if mmUserToken.defaultExpectation == nil {
		mmUserToken.defaultExpectation = &AuthMockUserTokenExpectation{}
	}

	if mmUserToken.defaultExpectation.params != nil {
		mmUserToken.mock.t.Fatalf("AuthMock.UserToken mock is already set by Expect")
	}

	if mmUserToken.defaultExpectation.paramPtrs == nil {
		mmUserToken.defaultExpectation.paramPtrs = &AuthMockUserTokenParamPtrs{}
	}
	mmUserToken.defaultExpectation.paramPtrs.email = &email
	mmUserToken.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmUserToken
}

// ExpectPasswordParam3 sets up expected param password for AuthService.UserToken
func (mmUserToken *mAuthMockUserToken) ExpectPasswordParam3(password string) *mAuthMockUserToken {
	if mmUserToken.mock.funcUserToken != nil {
		mmUserToken.mock.t.Fatalf("AuthMock.UserToken mock is already set by Set")
	}

	if mmUserToken.defaultExpectation == nil {
		mmUserToken.defaultExpectation = &AuthMockUserTokenExpectation{}
	}

	if mmUserToken.defaultExpectation.params != nil {
		mmUserToken.mock.t.Fatalf("AuthMock.UserToken mock is already set by Expect")
	}

	if mmUserToken.defaultExpectation.paramPtrs == nil {
		mmUserToken.defaultExpectation.paramPtrs = &AuthMockUserTokenParamPtrs{}
	}
	mmUserToken.defaultExpectation.paramPtrs.password = &password
	mmUserToken.defaultExpectation.expectationOrigins.originPassword = minimock.CallerInfo(1)

	return mmUserToken
}

// Inspect accepts an inspector function that has same arguments as the AuthService.UserToken
func (mmUserToken *mAuthMockUserToken) Inspect(f func(ctx context.Context, email string, password string)) *mAuthMockUserToken {
	if mmUserToken.mock.inspectFuncUserToken != nil {
		mmUserToken.mock.t.Fatalf("Inspect function is already set for AuthMock.UserToken")
	}

	mmUserToken.mock.inspectFuncUserToken = f

	return mmUserToken
}

// Return sets up results that will be returned by AuthService.UserToken
func (mmUserToken *mAuthMockUserToken) Return(s1 string, err error) *AuthMock {
	if mmUserToken.mock.funcUserToken != nil {
		mmUserToken.mock.t.Fatalf("AuthMock.UserToken mock is already set by Set")
	}

	if mmUserToken.defaultExpectation == nil {
		mmUserToken.defaultExpectation = &AuthMockUserTokenExpectation{mock: mmUserToken.mock}
	}
	mmUserToken.defaultExpectation.results = &AuthMockUserTokenResults{s1, err}
	mmUserToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUserToken.mock
}

// Set uses given function f to mock the AuthService.UserToken method
func (mmUserToken *mAuthMockUserToken) Set(f func(ctx context.Context, email string, password string) (s1 string, err error)) *AuthMock {
	if mmUserToken.defaultExpectation != nil {
		mmUserToken.mock.t.Fatalf("Default expectation is already set for the AuthService.UserToken method")
	}

	if len(mmUserToken.expectations) > 0 {
		mmUserToken.mock.t.Fatalf("Some expectations are already set for the AuthService.UserToken method")
	}

	mmUserToken.mock.funcUserToken = f
	mmUserToken.mock.funcUserTokenOrigin = minimock.CallerInfo(1)
	return mmUserToken.mock
}

// When sets expectation for the AuthService.UserToken which will trigger the result defined by the following
// Then helper
func (mmUserToken *mAuthMockUserToken) When(ctx context.Context, email string, password string) *AuthMockUserTokenExpectation {
	if mmUserToken.mock.funcUserToken != nil {
		mmUserToken.mock.t.Fatalf("AuthMock.UserToken mock is already set by Set")
	}

	expectation := &AuthMockUserTokenExpectation{
		mock:               mmUserToken.mock,
		params:             &AuthMockUserTokenParams{ctx, email, password},
		expectationOrigins: AuthMockUserTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUserToken.expectations = append(mmUserToken.expectations, expectation)
	return expectation
}

// Then sets up AuthService.UserToken return parameters for the expectation previously defined by the When method
func (e *AuthMockUserTokenExpectation) Then(s1 string, err error) *AuthMock {
	e.results = &AuthMockUserTokenResults{s1, err}
	return e.mock
}

// Times sets number of times AuthService.UserToken should be invoked
func (mmUserToken *mAuthMockUserToken) Times(n uint64) *mAuthMockUserToken {
	if n == 0 {
		mmUserToken.mock.t.Fatalf("Times of AuthMock.UserToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUserToken.expectedInvocations, n)
	mmUserToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUserToken
}

func (mmUserToken *mAuthMockUserToken) invocationsDone() bool {
	if len(mmUserToken.expectations) == 0 && mmUserToken.defaultExpectation == nil && mmUserToken.mock.funcUserToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUserToken.mock.afterUserTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUserToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UserToken implements mm_pvz.AuthService
func (mmUserToken *AuthMock) UserToken(ctx context.Context, email string, password string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmUserToken.beforeUserTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmUserToken.afterUserTokenCounter, 1)

	mmUserToken.t.Helper()

	if mmUserToken.inspectFuncUserToken != nil {
		mmUserToken.inspectFuncUserToken(ctx, email, password)
	}

	mm_params := AuthMockUserTokenParams{ctx, email, password}

	// Record call args
	mmUserToken.UserTokenMock.mutex.Lock()
	mmUserToken.UserTokenMock.callArgs = append(mmUserToken.UserTokenMock.callArgs, &mm_params)
	mmUserToken.UserTokenMock.mutex.Unlock()

	for _, e := range mmUserToken.UserTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmUserToken.UserTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUserToken.UserTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmUserToken.UserTokenMock.defaultExpectation.params
		mm_want_ptrs := mmUserToken.UserTokenMock.defaultExpectation.paramPtrs

		mm_got := AuthMockUserTokenParams{ctx, email, password}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUserToken.t.Errorf("AuthMock.UserToken got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUserToken.UserTokenMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmUserToken.t.Errorf("AuthMock.UserToken got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUserToken.UserTokenMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

			if mm_want_ptrs.password != nil && !minimock.Equal(*mm_want_ptrs.password, mm_got.password) {
				mmUserToken.t.Errorf("AuthMock.UserToken got unexpected parameter password, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUserToken.UserTokenMock.defaultExpectation.expectationOrigins.originPassword, *mm_want_ptrs.password, mm_got.password, minimock.Diff(*mm_want_ptrs.password, mm_got.password))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUserToken.t.Errorf("AuthMock.UserToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUserToken.UserTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUserToken.UserTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmUserToken.t.Fatal("No results are set for the AuthMock.UserToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmUserToken.funcUserToken != nil {
		return mmUserToken.funcUserToken(ctx, email, password)
	}
	mmUserToken.t.Fatalf("Unexpected call to AuthMock.UserToken. %v %v %v", ctx, email, password)
	return
}

// UserTokenAfterCounter returns a count of finished AuthMock.UserToken invocations
func (mmUserToken *AuthMock) UserTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUserToken.afterUserTokenCounter)
}

// UserTokenBeforeCounter returns a count of AuthMock.UserToken invocations
func (mmUserToken *AuthMock) UserTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUserToken.beforeUserTokenCounter)
}

// Calls returns a list of arguments used in each call to AuthMock.UserToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUserToken *mAuthMockUserToken) Calls() []*AuthMockUserTokenParams {
	mmUserToken.mutex.RLock()

	argCopy := make([]*AuthMockUserTokenParams, len(mmUserToken.callArgs))
	copy(argCopy, mmUserToken.callArgs)

	mmUserToken.mutex.RUnlock()

	return argCopy
}

// MinimockUserTokenDone returns true if the count of the UserToken invocations corresponds
// the number of defined expectations
func (m *AuthMock) MinimockUserTokenDone() bool {
	if m.UserTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UserTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UserTokenMock.invocationsDone()
}

// MinimockUserTokenInspect logs each unmet expectation
func (m *AuthMock) MinimockUserTokenInspect() {
	for _, e := range m.UserTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthMock.UserToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUserTokenCounter := mm_atomic.LoadUint64(&m.afterUserTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UserTokenMock.defaultExpectation != nil && afterUserTokenCounter < 1 {
		if m.UserTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthMock.UserToken at\n%s", m.UserTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthMock.UserToken at\n%s with params: %#v", m.UserTokenMock.defaultExpectation.expectationOrigins.origin, *m.UserTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUserToken != nil && afterUserTokenCounter < 1 {
		m.t.Errorf("Expected call to AuthMock.UserToken at\n%s", m.funcUserTokenOrigin)
	}

	if !m.UserTokenMock.invocationsDone() && afterUserTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthMock.UserToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UserTokenMock.expectedInvocations), m.UserTokenMock.expectedInvocationsOrigin, afterUserTokenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuthMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDummyLoginInspect()

			m.MinimockRegisterInspect()

			m.MinimockUserTokenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuthMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuthMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDummyLoginDone() &&
		m.MinimockRegisterDone() &&
		m.MinimockUserTokenDone()
}
