// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pvz.proto

package pvz_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListPVZRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListPVZRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPVZRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListPVZRequestMultiError,
// or nil if none found.
func (m *ListPVZRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPVZRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStartDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListPVZRequestValidationError{
					field:  "StartDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListPVZRequestValidationError{
					field:  "StartDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListPVZRequestValidationError{
				field:  "StartDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListPVZRequestValidationError{
					field:  "EndDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListPVZRequestValidationError{
					field:  "EndDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListPVZRequestValidationError{
				field:  "EndDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Page

	// no validation rules for Limit

	if len(errors) > 0 {
		return ListPVZRequestMultiError(errors)
	}

	return nil
}

// ListPVZRequestMultiError is an error wrapping multiple validation errors
// returned by ListPVZRequest.ValidateAll() if the designated constraints
// aren't met.
type ListPVZRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPVZRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPVZRequestMultiError) AllErrors() []error { return m }

// ListPVZRequestValidationError is the validation error returned by
// ListPVZRequest.Validate if the designated constraints aren't met.
type ListPVZRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPVZRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPVZRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPVZRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPVZRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPVZRequestValidationError) ErrorName() string { return "ListPVZRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListPVZRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPVZRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPVZRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPVZRequestValidationError{}

// Validate checks the field values on ListPVZResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListPVZResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPVZResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPVZResponseMultiError, or nil if none found.
func (m *ListPVZResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPVZResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPvzs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListPVZResponseValidationError{
						field:  fmt.Sprintf("Pvzs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListPVZResponseValidationError{
						field:  fmt.Sprintf("Pvzs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPVZResponseValidationError{
					field:  fmt.Sprintf("Pvzs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListPVZResponseMultiError(errors)
	}

	return nil
}

// ListPVZResponseMultiError is an error wrapping multiple validation errors
// returned by ListPVZResponse.ValidateAll() if the designated constraints
// aren't met.
type ListPVZResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPVZResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPVZResponseMultiError) AllErrors() []error { return m }

// ListPVZResponseValidationError is the validation error returned by
// ListPVZResponse.Validate if the designated constraints aren't met.
type ListPVZResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPVZResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPVZResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPVZResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPVZResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPVZResponseValidationError) ErrorName() string { return "ListPVZResponseValidationError" }

// Error satisfies the builtin error interface
func (e ListPVZResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPVZResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPVZResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPVZResponseValidationError{}

// Validate checks the field values on CreatePVZRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreatePVZRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreatePVZRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreatePVZRequestMultiError, or nil if none found.
func (m *CreatePVZRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreatePVZRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for City

	if len(errors) > 0 {
		return CreatePVZRequestMultiError(errors)
	}

	return nil
}

// CreatePVZRequestMultiError is an error wrapping multiple validation errors
// returned by CreatePVZRequest.ValidateAll() if the designated constraints
// aren't met.
type CreatePVZRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatePVZRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatePVZRequestMultiError) AllErrors() []error { return m }

// CreatePVZRequestValidationError is the validation error returned by
// CreatePVZRequest.Validate if the designated constraints aren't met.
type CreatePVZRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePVZRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePVZRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePVZRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePVZRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePVZRequestValidationError) ErrorName() string { return "CreatePVZRequestValidationError" }

// Error satisfies the builtin error interface
func (e CreatePVZRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePVZRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePVZRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePVZRequestValidationError{}

// Validate checks the field values on CreatePVZResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreatePVZResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreatePVZResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreatePVZResponseMultiError, or nil if none found.
func (m *CreatePVZResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreatePVZResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPvz()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreatePVZResponseValidationError{
					field:  "Pvz",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreatePVZResponseValidationError{
					field:  "Pvz",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPvz()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreatePVZResponseValidationError{
				field:  "Pvz",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreatePVZResponseMultiError(errors)
	}

	return nil
}

// CreatePVZResponseMultiError is an error wrapping multiple validation errors
// returned by CreatePVZResponse.ValidateAll() if the designated constraints
// aren't met.
type CreatePVZResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatePVZResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatePVZResponseMultiError) AllErrors() []error { return m }

// CreatePVZResponseValidationError is the validation error returned by
// CreatePVZResponse.Validate if the designated constraints aren't met.
type CreatePVZResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePVZResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePVZResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePVZResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePVZResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePVZResponseValidationError) ErrorName() string {
	return "CreatePVZResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePVZResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePVZResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePVZResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePVZResponseValidationError{}

// Validate checks the field values on CreateReceptionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateReceptionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReceptionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateReceptionRequestMultiError, or nil if none found.
func (m *CreateReceptionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReceptionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PvzId

	if len(errors) > 0 {
		return CreateReceptionRequestMultiError(errors)
	}

	return nil
}

// CreateReceptionRequestMultiError is an error wrapping multiple validation
// errors returned by CreateReceptionRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateReceptionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReceptionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReceptionRequestMultiError) AllErrors() []error { return m }

// CreateReceptionRequestValidationError is the validation error returned by
// CreateReceptionRequest.Validate if the designated constraints aren't met.
type CreateReceptionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReceptionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReceptionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReceptionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReceptionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReceptionRequestValidationError) ErrorName() string {
	return "CreateReceptionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReceptionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReceptionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReceptionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReceptionRequestValidationError{}

// Validate checks the field values on CreateReceptionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateReceptionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReceptionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateReceptionResponseMultiError, or nil if none found.
func (m *CreateReceptionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReceptionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetReception()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateReceptionResponseValidationError{
					field:  "Reception",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateReceptionResponseValidationError{
					field:  "Reception",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReception()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateReceptionResponseValidationError{
				field:  "Reception",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateReceptionResponseMultiError(errors)
	}

	return nil
}

// CreateReceptionResponseMultiError is an error wrapping multiple validation
// errors returned by CreateReceptionResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateReceptionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReceptionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReceptionResponseMultiError) AllErrors() []error { return m }

// CreateReceptionResponseValidationError is the validation error returned by
// CreateReceptionResponse.Validate if the designated constraints aren't met.
type CreateReceptionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReceptionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReceptionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReceptionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReceptionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReceptionResponseValidationError) ErrorName() string {
	return "CreateReceptionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReceptionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReceptionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReceptionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReceptionResponseValidationError{}

// Validate checks the field values on CloseLastReceptionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CloseLastReceptionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CloseLastReceptionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CloseLastReceptionRequestMultiError, or nil if none found.
func (m *CloseLastReceptionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CloseLastReceptionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PvzId

	if len(errors) > 0 {
		return CloseLastReceptionRequestMultiError(errors)
	}

	return nil
}

// CloseLastReceptionRequestMultiError is an error wrapping multiple validation
// errors returned by CloseLastReceptionRequest.ValidateAll() if the
// designated constraints aren't met.
type CloseLastReceptionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CloseLastReceptionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CloseLastReceptionRequestMultiError) AllErrors() []error { return m }

// CloseLastReceptionRequestValidationError is the validation error returned by
// CloseLastReceptionRequest.Validate if the designated constraints aren't met.
type CloseLastReceptionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CloseLastReceptionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CloseLastReceptionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CloseLastReceptionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CloseLastReceptionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CloseLastReceptionRequestValidationError) ErrorName() string {
	return "CloseLastReceptionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CloseLastReceptionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCloseLastReceptionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CloseLastReceptionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CloseLastReceptionRequestValidationError{}

// Validate checks the field values on CloseLastReceptionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CloseLastReceptionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CloseLastReceptionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CloseLastReceptionResponseMultiError, or nil if none found.
func (m *CloseLastReceptionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CloseLastReceptionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetReception()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CloseLastReceptionResponseValidationError{
					field:  "Reception",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CloseLastReceptionResponseValidationError{
					field:  "Reception",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReception()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CloseLastReceptionResponseValidationError{
				field:  "Reception",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CloseLastReceptionResponseMultiError(errors)
	}

	return nil
}

// CloseLastReceptionResponseMultiError is an error wrapping multiple
// validation errors returned by CloseLastReceptionResponse.ValidateAll() if
// the designated constraints aren't met.
type CloseLastReceptionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CloseLastReceptionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CloseLastReceptionResponseMultiError) AllErrors() []error { return m }

// CloseLastReceptionResponseValidationError is the validation error returned
// by CloseLastReceptionResponse.Validate if the designated constraints aren't met.
type CloseLastReceptionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CloseLastReceptionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CloseLastReceptionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CloseLastReceptionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CloseLastReceptionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CloseLastReceptionResponseValidationError) ErrorName() string {
	return "CloseLastReceptionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CloseLastReceptionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCloseLastReceptionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CloseLastReceptionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CloseLastReceptionResponseValidationError{}

// Validate checks the field values on CreateProductRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateProductRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateProductRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateProductRequestMultiError, or nil if none found.
func (m *CreateProductRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateProductRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for PvzId

	if len(errors) > 0 {
		return CreateProductRequestMultiError(errors)
	}

	return nil
}

// CreateProductRequestMultiError is an error wrapping multiple validation
// errors returned by CreateProductRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateProductRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateProductRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateProductRequestMultiError) AllErrors() []error { return m }

// CreateProductRequestValidationError is the validation error returned by
// CreateProductRequest.Validate if the designated constraints aren't met.
type CreateProductRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateProductRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateProductRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateProductRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateProductRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateProductRequestValidationError) ErrorName() string {
	return "CreateProductRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateProductRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateProductRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateProductRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateProductRequestValidationError{}

// Validate checks the field values on CreateProductResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateProductResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateProductResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateProductResponseMultiError, or nil if none found.
func (m *CreateProductResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateProductResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProduct()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateProductResponseValidationError{
					field:  "Product",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateProductResponseValidationError{
					field:  "Product",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProduct()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateProductResponseValidationError{
				field:  "Product",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateProductResponseMultiError(errors)
	}

	return nil
}

// CreateProductResponseMultiError is an error wrapping multiple validation
// errors returned by CreateProductResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateProductResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateProductResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateProductResponseMultiError) AllErrors() []error { return m }

// CreateProductResponseValidationError is the validation error returned by
// CreateProductResponse.Validate if the designated constraints aren't met.
type CreateProductResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateProductResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateProductResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateProductResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateProductResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateProductResponseValidationError) ErrorName() string {
	return "CreateProductResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateProductResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateProductResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateProductResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateProductResponseValidationError{}

// Validate checks the field values on DeleteLastProductRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteLastProductRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteLastProductRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteLastProductRequestMultiError, or nil if none found.
func (m *DeleteLastProductRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteLastProductRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PvzId

	if len(errors) > 0 {
		return DeleteLastProductRequestMultiError(errors)
	}

	return nil
}

// DeleteLastProductRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteLastProductRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteLastProductRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteLastProductRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteLastProductRequestMultiError) AllErrors() []error { return m }

// DeleteLastProductRequestValidationError is the validation error returned by
// DeleteLastProductRequest.Validate if the designated constraints aren't met.
type DeleteLastProductRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteLastProductRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteLastProductRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteLastProductRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteLastProductRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteLastProductRequestValidationError) ErrorName() string {
	return "DeleteLastProductRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteLastProductRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteLastProductRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteLastProductRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteLastProductRequestValidationError{}

// Validate checks the field values on DeleteLastProductResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteLastProductResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteLastProductResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteLastProductResponseMultiError, or nil if none found.
func (m *DeleteLastProductResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteLastProductResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return DeleteLastProductResponseMultiError(errors)
	}

	return nil
}

// DeleteLastProductResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteLastProductResponse.ValidateAll() if the
// designated constraints aren't met.
type DeleteLastProductResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteLastProductResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteLastProductResponseMultiError) AllErrors() []error { return m }

// DeleteLastProductResponseValidationError is the validation error returned by
// DeleteLastProductResponse.Validate if the designated constraints aren't met.
type DeleteLastProductResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteLastProductResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteLastProductResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteLastProductResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteLastProductResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteLastProductResponseValidationError) ErrorName() string {
	return "DeleteLastProductResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteLastProductResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteLastProductResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteLastProductResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteLastProductResponseValidationError{}

// Validate checks the field values on DummyLoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DummyLoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DummyLoginRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DummyLoginRequestMultiError, or nil if none found.
func (m *DummyLoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DummyLoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Role

	if len(errors) > 0 {
		return DummyLoginRequestMultiError(errors)
	}

	return nil
}

// DummyLoginRequestMultiError is an error wrapping multiple validation errors
// returned by DummyLoginRequest.ValidateAll() if the designated constraints
// aren't met.
type DummyLoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DummyLoginRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DummyLoginRequestMultiError) AllErrors() []error { return m }

// DummyLoginRequestValidationError is the validation error returned by
// DummyLoginRequest.Validate if the designated constraints aren't met.
type DummyLoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DummyLoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DummyLoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DummyLoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DummyLoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DummyLoginRequestValidationError) ErrorName() string {
	return "DummyLoginRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DummyLoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDummyLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DummyLoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DummyLoginRequestValidationError{}

// Validate checks the field values on DummyLoginResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DummyLoginResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DummyLoginResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DummyLoginResponseMultiError, or nil if none found.
func (m *DummyLoginResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DummyLoginResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return DummyLoginResponseMultiError(errors)
	}

	return nil
}

// DummyLoginResponseMultiError is an error wrapping multiple validation errors
// returned by DummyLoginResponse.ValidateAll() if the designated constraints
// aren't met.
type DummyLoginResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DummyLoginResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DummyLoginResponseMultiError) AllErrors() []error { return m }

// DummyLoginResponseValidationError is the validation error returned by
// DummyLoginResponse.Validate if the designated constraints aren't met.
type DummyLoginResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DummyLoginResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DummyLoginResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DummyLoginResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DummyLoginResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DummyLoginResponseValidationError) ErrorName() string {
	return "DummyLoginResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DummyLoginResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDummyLoginResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DummyLoginResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DummyLoginResponseValidationError{}

// Validate checks the field values on RegisterRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RegisterRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterRequestMultiError, or nil if none found.
func (m *RegisterRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Email

	// no validation rules for Password

	// no validation rules for Role

	if len(errors) > 0 {
		return RegisterRequestMultiError(errors)
	}

	return nil
}

// RegisterRequestMultiError is an error wrapping multiple validation errors
// returned by RegisterRequest.ValidateAll() if the designated constraints
// aren't met.
type RegisterRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterRequestMultiError) AllErrors() []error { return m }

// RegisterRequestValidationError is the validation error returned by
// RegisterRequest.Validate if the designated constraints aren't met.
type RegisterRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterRequestValidationError) ErrorName() string { return "RegisterRequestValidationError" }

// Error satisfies the builtin error interface
func (e RegisterRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterRequestValidationError{}

// Validate checks the field values on RegisterResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RegisterResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterResponseMultiError, or nil if none found.
func (m *RegisterResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Email

	// no validation rules for Role

	if len(errors) > 0 {
		return RegisterResponseMultiError(errors)
	}

	return nil
}

// RegisterResponseMultiError is an error wrapping multiple validation errors
// returned by RegisterResponse.ValidateAll() if the designated constraints
// aren't met.
type RegisterResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterResponseMultiError) AllErrors() []error { return m }

// RegisterResponseValidationError is the validation error returned by
// RegisterResponse.Validate if the designated constraints aren't met.
type RegisterResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterResponseValidationError) ErrorName() string { return "RegisterResponseValidationError" }

// Error satisfies the builtin error interface
func (e RegisterResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterResponseValidationError{}

// Validate checks the field values on LoginRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LoginRequestMultiError, or
// nil if none found.
func (m *LoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = LoginRequestValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Password

	if len(errors) > 0 {
		return LoginRequestMultiError(errors)
	}

	return nil
}

func (m *LoginRequest) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *LoginRequest) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// LoginRequestMultiError is an error wrapping multiple validation errors
// returned by LoginRequest.ValidateAll() if the designated constraints aren't met.
type LoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginRequestMultiError) AllErrors() []error { return m }

// LoginRequestValidationError is the validation error returned by
// LoginRequest.Validate if the designated constraints aren't met.
type LoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginRequestValidationError) ErrorName() string { return "LoginRequestValidationError" }

// Error satisfies the builtin error interface
func (e LoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginRequestValidationError{}

// Validate checks the field values on LoginResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LoginResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LoginResponseMultiError, or
// nil if none found.
func (m *LoginResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return LoginResponseMultiError(errors)
	}

	return nil
}

// LoginResponseMultiError is an error wrapping multiple validation errors
// returned by LoginResponse.ValidateAll() if the designated constraints
// aren't met.
type LoginResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginResponseMultiError) AllErrors() []error { return m }

// LoginResponseValidationError is the validation error returned by
// LoginResponse.Validate if the designated constraints aren't met.
type LoginResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginResponseValidationError) ErrorName() string { return "LoginResponseValidationError" }

// Error satisfies the builtin error interface
func (e LoginResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginResponseValidationError{}

// Validate checks the field values on GetPVZListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPVZListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPVZListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPVZListResponseMultiError, or nil if none found.
func (m *GetPVZListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPVZListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPvzs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetPVZListResponseValidationError{
						field:  fmt.Sprintf("Pvzs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetPVZListResponseValidationError{
						field:  fmt.Sprintf("Pvzs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetPVZListResponseValidationError{
					field:  fmt.Sprintf("Pvzs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetPVZListResponseMultiError(errors)
	}

	return nil
}

// GetPVZListResponseMultiError is an error wrapping multiple validation errors
// returned by GetPVZListResponse.ValidateAll() if the designated constraints
// aren't met.
type GetPVZListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPVZListResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPVZListResponseMultiError) AllErrors() []error { return m }

// GetPVZListResponseValidationError is the validation error returned by
// GetPVZListResponse.Validate if the designated constraints aren't met.
type GetPVZListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPVZListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPVZListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPVZListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPVZListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPVZListResponseValidationError) ErrorName() string {
	return "GetPVZListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetPVZListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPVZListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPVZListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPVZListResponseValidationError{}

// Validate checks the field values on PVZ with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *PVZ) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PVZ with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PVZMultiError, or nil if none found.
func (m *PVZ) ValidateAll() error {
	return m.validate(true)
}

func (m *PVZ) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetRegistrationDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PVZValidationError{
					field:  "RegistrationDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PVZValidationError{
					field:  "RegistrationDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRegistrationDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PVZValidationError{
				field:  "RegistrationDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for City

	if len(errors) > 0 {
		return PVZMultiError(errors)
	}

	return nil
}

// PVZMultiError is an error wrapping multiple validation errors returned by
// PVZ.ValidateAll() if the designated constraints aren't met.
type PVZMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PVZMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PVZMultiError) AllErrors() []error { return m }

// PVZValidationError is the validation error returned by PVZ.Validate if the
// designated constraints aren't met.
type PVZValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PVZValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PVZValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PVZValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PVZValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PVZValidationError) ErrorName() string { return "PVZValidationError" }

// Error satisfies the builtin error interface
func (e PVZValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPVZ.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PVZValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PVZValidationError{}

// Validate checks the field values on Reception with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Reception) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Reception with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReceptionMultiError, or nil
// if none found.
func (m *Reception) ValidateAll() error {
	return m.validate(true)
}

func (m *Reception) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetDateTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReceptionValidationError{
					field:  "DateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReceptionValidationError{
					field:  "DateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDateTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReceptionValidationError{
				field:  "DateTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for PvzId

	// no validation rules for Status

	if len(errors) > 0 {
		return ReceptionMultiError(errors)
	}

	return nil
}

// ReceptionMultiError is an error wrapping multiple validation errors returned
// by Reception.ValidateAll() if the designated constraints aren't met.
type ReceptionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReceptionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReceptionMultiError) AllErrors() []error { return m }

// ReceptionValidationError is the validation error returned by
// Reception.Validate if the designated constraints aren't met.
type ReceptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReceptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReceptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReceptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReceptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReceptionValidationError) ErrorName() string { return "ReceptionValidationError" }

// Error satisfies the builtin error interface
func (e ReceptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReception.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReceptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReceptionValidationError{}

// Validate checks the field values on Product with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Product) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Product with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ProductMultiError, or nil if none found.
func (m *Product) ValidateAll() error {
	return m.validate(true)
}

func (m *Product) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetDateTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProductValidationError{
					field:  "DateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProductValidationError{
					field:  "DateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDateTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProductValidationError{
				field:  "DateTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Type

	// no validation rules for ReceptionId

	if len(errors) > 0 {
		return ProductMultiError(errors)
	}

	return nil
}

// ProductMultiError is an error wrapping multiple validation errors returned
// by Product.ValidateAll() if the designated constraints aren't met.
type ProductMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductMultiError) AllErrors() []error { return m }

// ProductValidationError is the validation error returned by Product.Validate
// if the designated constraints aren't met.
type ProductValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductValidationError) ErrorName() string { return "ProductValidationError" }

// Error satisfies the builtin error interface
func (e ProductValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProduct.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductValidationError{}

// Validate checks the field values on ListPVZResponseReceptionInfo with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPVZResponseReceptionInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPVZResponseReceptionInfo with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPVZResponseReceptionInfoMultiError, or nil if none found.
func (m *ListPVZResponseReceptionInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPVZResponseReceptionInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetReception()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListPVZResponseReceptionInfoValidationError{
					field:  "Reception",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListPVZResponseReceptionInfoValidationError{
					field:  "Reception",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReception()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListPVZResponseReceptionInfoValidationError{
				field:  "Reception",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetProducts() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListPVZResponseReceptionInfoValidationError{
						field:  fmt.Sprintf("ProductsByReceptionId[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListPVZResponseReceptionInfoValidationError{
						field:  fmt.Sprintf("ProductsByReceptionId[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPVZResponseReceptionInfoValidationError{
					field:  fmt.Sprintf("ProductsByReceptionId[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListPVZResponseReceptionInfoMultiError(errors)
	}

	return nil
}

// ListPVZResponseReceptionInfoMultiError is an error wrapping multiple
// validation errors returned by ListPVZResponseReceptionInfo.ValidateAll() if
// the designated constraints aren't met.
type ListPVZResponseReceptionInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPVZResponseReceptionInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPVZResponseReceptionInfoMultiError) AllErrors() []error { return m }

// ListPVZResponseReceptionInfoValidationError is the validation error returned
// by ListPVZResponseReceptionInfo.Validate if the designated constraints
// aren't met.
type ListPVZResponseReceptionInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPVZResponseReceptionInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPVZResponseReceptionInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPVZResponseReceptionInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPVZResponseReceptionInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPVZResponseReceptionInfoValidationError) ErrorName() string {
	return "ListPVZResponseReceptionInfoValidationError"
}

// Error satisfies the builtin error interface
func (e ListPVZResponseReceptionInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPVZResponseReceptionInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPVZResponseReceptionInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPVZResponseReceptionInfoValidationError{}

// Validate checks the field values on ListPVZResponsePvzInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPVZResponsePvzInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPVZResponsePvzInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPVZResponsePvzInfoMultiError, or nil if none found.
func (m *ListPVZResponsePvzInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPVZResponsePvzInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPvz()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListPVZResponsePvzInfoValidationError{
					field:  "Pvz",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListPVZResponsePvzInfoValidationError{
					field:  "Pvz",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPvz()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListPVZResponsePvzInfoValidationError{
				field:  "Pvz",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetReceptions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListPVZResponsePvzInfoValidationError{
						field:  fmt.Sprintf("ReceptionsByPVZId[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListPVZResponsePvzInfoValidationError{
						field:  fmt.Sprintf("ReceptionsByPVZId[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPVZResponsePvzInfoValidationError{
					field:  fmt.Sprintf("ReceptionsByPVZId[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListPVZResponsePvzInfoMultiError(errors)
	}

	return nil
}

// ListPVZResponsePvzInfoMultiError is an error wrapping multiple validation
// errors returned by ListPVZResponsePvzInfo.ValidateAll() if the designated
// constraints aren't met.
type ListPVZResponsePvzInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPVZResponsePvzInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPVZResponsePvzInfoMultiError) AllErrors() []error { return m }

// ListPVZResponsePvzInfoValidationError is the validation error returned by
// ListPVZResponsePvzInfo.Validate if the designated constraints aren't met.
type ListPVZResponsePvzInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPVZResponsePvzInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPVZResponsePvzInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPVZResponsePvzInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPVZResponsePvzInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPVZResponsePvzInfoValidationError) ErrorName() string {
	return "ListPVZResponsePvzInfoValidationError"
}

// Error satisfies the builtin error interface
func (e ListPVZResponsePvzInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPVZResponsePvzInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPVZResponsePvzInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPVZResponsePvzInfoValidationError{}
