// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.14.0
// source: pvz.proto

package pvz_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPVZRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=endDate,proto3" json:"endDate,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPVZRequest) Reset() {
	*x = ListPVZRequest{}
	mi := &file_pvz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPVZRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPVZRequest) ProtoMessage() {}

func (x *ListPVZRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPVZRequest.ProtoReflect.Descriptor instead.
func (*ListPVZRequest) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{0}
}

func (x *ListPVZRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ListPVZRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *ListPVZRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPVZRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListPVZResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pvzs          []*ListPVZResponsePvzInfo `protobuf:"bytes,1,rep,name=pvzs,proto3" json:"pvzs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPVZResponse) Reset() {
	*x = ListPVZResponse{}
	mi := &file_pvz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPVZResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPVZResponse) ProtoMessage() {}

func (x *ListPVZResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPVZResponse.ProtoReflect.Descriptor instead.
func (*ListPVZResponse) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{1}
}

func (x *ListPVZResponse) GetPvzs() []*ListPVZResponsePvzInfo {
	if x != nil {
		return x.Pvzs
	}
	return nil
}

type CreatePVZRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	RegistrationDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=registrationDate,proto3,oneof" json:"registrationDate,omitempty"`
	City             string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePVZRequest) Reset() {
	*x = CreatePVZRequest{}
	mi := &file_pvz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePVZRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePVZRequest) ProtoMessage() {}

func (x *CreatePVZRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePVZRequest.ProtoReflect.Descriptor instead.
func (*CreatePVZRequest) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePVZRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CreatePVZRequest) GetRegistrationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationDate
	}
	return nil
}

func (x *CreatePVZRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type CreatePVZResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pvz           *PVZ                   `protobuf:"bytes,1,opt,name=pvz,proto3" json:"pvz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePVZResponse) Reset() {
	*x = CreatePVZResponse{}
	mi := &file_pvz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePVZResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePVZResponse) ProtoMessage() {}

func (x *CreatePVZResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePVZResponse.ProtoReflect.Descriptor instead.
func (*CreatePVZResponse) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePVZResponse) GetPvz() *PVZ {
	if x != nil {
		return x.Pvz
	}
	return nil
}

type CreateReceptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PvzId         string                 `protobuf:"bytes,1,opt,name=pvzId,proto3" json:"pvzId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReceptionRequest) Reset() {
	*x = CreateReceptionRequest{}
	mi := &file_pvz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReceptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceptionRequest) ProtoMessage() {}

func (x *CreateReceptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceptionRequest.ProtoReflect.Descriptor instead.
func (*CreateReceptionRequest) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReceptionRequest) GetPvzId() string {
	if x != nil {
		return x.PvzId
	}
	return ""
}

type CreateReceptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reception     *Reception             `protobuf:"bytes,1,opt,name=reception,proto3" json:"reception,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReceptionResponse) Reset() {
	*x = CreateReceptionResponse{}
	mi := &file_pvz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReceptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceptionResponse) ProtoMessage() {}

func (x *CreateReceptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceptionResponse.ProtoReflect.Descriptor instead.
func (*CreateReceptionResponse) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReceptionResponse) GetReception() *Reception {
	if x != nil {
		return x.Reception
	}
	return nil
}

type CloseLastReceptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PvzId         string                 `protobuf:"bytes,1,opt,name=pvzId,proto3" json:"pvzId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseLastReceptionRequest) Reset() {
	*x = CloseLastReceptionRequest{}
	mi := &file_pvz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseLastReceptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseLastReceptionRequest) ProtoMessage() {}

func (x *CloseLastReceptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseLastReceptionRequest.ProtoReflect.Descriptor instead.
func (*CloseLastReceptionRequest) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{6}
}

func (x *CloseLastReceptionRequest) GetPvzId() string {
	if x != nil {
		return x.PvzId
	}
	return ""
}

type CloseLastReceptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reception     *Reception             `protobuf:"bytes,1,opt,name=reception,proto3" json:"reception,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseLastReceptionResponse) Reset() {
	*x = CloseLastReceptionResponse{}
	mi := &file_pvz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseLastReceptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseLastReceptionResponse) ProtoMessage() {}

func (x *CloseLastReceptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseLastReceptionResponse.ProtoReflect.Descriptor instead.
func (*CloseLastReceptionResponse) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{7}
}

func (x *CloseLastReceptionResponse) GetReception() *Reception {
	if x != nil {
		return x.Reception
	}
	return nil
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	PvzId         string                 `protobuf:"bytes,2,opt,name=pvzId,proto3" json:"pvzId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_pvz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{8}
}

func (x *CreateProductRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateProductRequest) GetPvzId() string {
	if x != nil {
		return x.PvzId
	}
	return ""
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_pvz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{9}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteLastProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PvzId         string                 `protobuf:"bytes,1,opt,name=pvzId,proto3" json:"pvzId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLastProductRequest) Reset() {
	*x = DeleteLastProductRequest{}
	mi := &file_pvz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLastProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLastProductRequest) ProtoMessage() {}

func (x *DeleteLastProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLastProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteLastProductRequest) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteLastProductRequest) GetPvzId() string {
	if x != nil {
		return x.PvzId
	}
	return ""
}

type DeleteLastProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLastProductResponse) Reset() {
	*x = DeleteLastProductResponse{}
	mi := &file_pvz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLastProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLastProductResponse) ProtoMessage() {}

func (x *DeleteLastProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLastProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteLastProductResponse) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteLastProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DummyLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyLoginRequest) Reset() {
	*x = DummyLoginRequest{}
	mi := &file_pvz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyLoginRequest) ProtoMessage() {}

func (x *DummyLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyLoginRequest.ProtoReflect.Descriptor instead.
func (*DummyLoginRequest) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{12}
}

func (x *DummyLoginRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type DummyLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyLoginResponse) Reset() {
	*x = DummyLoginResponse{}
	mi := &file_pvz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyLoginResponse) ProtoMessage() {}

func (x *DummyLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyLoginResponse.ProtoReflect.Descriptor instead.
func (*DummyLoginResponse) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{13}
}

func (x *DummyLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pvz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pvz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_pvz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{16}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_pvz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{17}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetPVZListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pvzs          []*PVZ                 `protobuf:"bytes,1,rep,name=pvzs,proto3" json:"pvzs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPVZListResponse) Reset() {
	*x = GetPVZListResponse{}
	mi := &file_pvz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPVZListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPVZListResponse) ProtoMessage() {}

func (x *GetPVZListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPVZListResponse.ProtoReflect.Descriptor instead.
func (*GetPVZListResponse) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{18}
}

func (x *GetPVZListResponse) GetPvzs() []*PVZ {
	if x != nil {
		return x.Pvzs
	}
	return nil
}

type PVZ struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	RegistrationDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=registration_date,json=registrationDate,proto3,oneof" json:"registration_date,omitempty"`
	City             string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PVZ) Reset() {
	*x = PVZ{}
	mi := &file_pvz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVZ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVZ) ProtoMessage() {}

func (x *PVZ) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVZ.ProtoReflect.Descriptor instead.
func (*PVZ) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{19}
}

func (x *PVZ) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *PVZ) GetRegistrationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationDate
	}
	return nil
}

func (x *PVZ) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type Reception struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	PvzId         string                 `protobuf:"bytes,3,opt,name=pvz_id,json=pvzId,proto3" json:"pvz_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reception) Reset() {
	*x = Reception{}
	mi := &file_pvz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reception) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reception) ProtoMessage() {}

func (x *Reception) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reception.ProtoReflect.Descriptor instead.
func (*Reception) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{20}
}

func (x *Reception) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reception) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *Reception) GetPvzId() string {
	if x != nil {
		return x.PvzId
	}
	return ""
}

func (x *Reception) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ReceptionId   string                 `protobuf:"bytes,4,opt,name=reception_id,json=receptionId,proto3" json:"reception_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_pvz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{21}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *Product) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Product) GetReceptionId() string {
	if x != nil {
		return x.ReceptionId
	}
	return ""
}

type ListPVZResponseReceptionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reception     *Reception             `protobuf:"bytes,1,opt,name=reception,proto3" json:"reception,omitempty"`
	Products      []*Product             `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPVZResponseReceptionInfo) Reset() {
	*x = ListPVZResponseReceptionInfo{}
	mi := &file_pvz_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPVZResponseReceptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPVZResponseReceptionInfo) ProtoMessage() {}

func (x *ListPVZResponseReceptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPVZResponseReceptionInfo.ProtoReflect.Descriptor instead.
func (*ListPVZResponseReceptionInfo) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListPVZResponseReceptionInfo) GetReception() *Reception {
	if x != nil {
		return x.Reception
	}
	return nil
}

func (x *ListPVZResponseReceptionInfo) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type ListPVZResponsePvzInfo struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Pvz           *PVZ                            `protobuf:"bytes,1,opt,name=pvz,proto3" json:"pvz,omitempty"`
	Receptions    []*ListPVZResponseReceptionInfo `protobuf:"bytes,2,rep,name=receptions,proto3" json:"receptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPVZResponsePvzInfo) Reset() {
	*x = ListPVZResponsePvzInfo{}
	mi := &file_pvz_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPVZResponsePvzInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPVZResponsePvzInfo) ProtoMessage() {}

func (x *ListPVZResponsePvzInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPVZResponsePvzInfo.ProtoReflect.Descriptor instead.
func (*ListPVZResponsePvzInfo) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ListPVZResponsePvzInfo) GetPvz() *PVZ {
	if x != nil {
		return x.Pvz
	}
	return nil
}

func (x *ListPVZResponsePvzInfo) GetReceptions() []*ListPVZResponseReceptionInfo {
	if x != nil {
		return x.Receptions
	}
	return nil
}

var File_pvz_proto protoreflect.FileDescriptor

const file_pvz_proto_rawDesc = "" +
	"\n" +
	"\tpvz.proto\x12\x06pvz.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\"\xaa\x01\n" +
	"\x0eListPVZRequest\x128\n" +
	"\tstartDate\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x124\n" +
	"\aendDate\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"\xa6\x02\n" +
	"\x0fListPVZResponse\x123\n" +
	"\x04pvzs\x18\x01 \x03(\v2\x1f.pvz.v1.ListPVZResponse.pvzInfoR\x04pvzs\x1am\n" +
	"\rreceptionInfo\x12/\n" +
	"\treception\x18\x01 \x01(\v2\x11.pvz.v1.ReceptionR\treception\x12+\n" +
	"\bproducts\x18\x02 \x03(\v2\x0f.pvz.v1.ProductR\bproducts\x1ao\n" +
	"\apvzInfo\x12\x1d\n" +
	"\x03pvz\x18\x01 \x01(\v2\v.pvz.v1.PVZR\x03pvz\x12E\n" +
	"\n" +
	"receptions\x18\x02 \x03(\v2%.pvz.v1.ListPVZResponse.receptionInfoR\n" +
	"receptions\"\xa4\x01\n" +
	"\x10CreatePVZRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12K\n" +
	"\x10registrationDate\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x10registrationDate\x88\x01\x01\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04cityB\x05\n" +
	"\x03_idB\x13\n" +
	"\x11_registrationDate\"2\n" +
	"\x11CreatePVZResponse\x12\x1d\n" +
	"\x03pvz\x18\x01 \x01(\v2\v.pvz.v1.PVZR\x03pvz\".\n" +
	"\x16CreateReceptionRequest\x12\x14\n" +
	"\x05pvzId\x18\x01 \x01(\tR\x05pvzId\"J\n" +
	"\x17CreateReceptionResponse\x12/\n" +
	"\treception\x18\x01 \x01(\v2\x11.pvz.v1.ReceptionR\treception\"1\n" +
	"\x19CloseLastReceptionRequest\x12\x14\n" +
	"\x05pvzId\x18\x01 \x01(\tR\x05pvzId\"M\n" +
	"\x1aCloseLastReceptionResponse\x12/\n" +
	"\treception\x18\x01 \x01(\v2\x11.pvz.v1.ReceptionR\treception\"@\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05pvzId\x18\x02 \x01(\tR\x05pvzId\"B\n" +
	"\x15CreateProductResponse\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.pvz.v1.ProductR\aproduct\"0\n" +
	"\x18DeleteLastProductRequest\x12\x14\n" +
	"\x05pvzId\x18\x01 \x01(\tR\x05pvzId\"5\n" +
	"\x19DeleteLastProductResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\x11DummyLoginRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"*\n" +
	"\x12DummyLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"i\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\bR\bpassword\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"L\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"I\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"5\n" +
	"\x12GetPVZListResponse\x12\x1f\n" +
	"\x04pvzs\x18\x01 \x03(\v2\v.pvz.v1.PVZR\x04pvzs\"\x99\x01\n" +
	"\x03PVZ\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12L\n" +
	"\x11registration_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x10registrationDate\x88\x01\x01\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04cityB\x05\n" +
	"\x03_idB\x14\n" +
	"\x12_registration_date\"\x83\x01\n" +
	"\tReception\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\tdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x15\n" +
	"\x06pvz_id\x18\x03 \x01(\tR\x05pvzId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x89\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\tdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12!\n" +
	"\freception_id\x18\x04 \x01(\tR\vreceptionId2\xea\a\n" +
	"\n" +
	"PVZService\x12N\n" +
	"\aListPVZ\x12\x16.pvz.v1.ListPVZRequest\x1a\x17.pvz.v1.ListPVZResponse\"\x12\x82\xd3\xe4\x93\x02\fb\x04pvzs\x12\x04/pvz\x12S\n" +
	"\tCreatePVZ\x12\x18.pvz.v1.CreatePVZRequest\x1a\x19.pvz.v1.CreatePVZResponse\"\x11\x82\xd3\xe4\x93\x02\vb\x03pvz\"\x04/pvz\x12r\n" +
	"\x0fCreateReception\x12\x1e.pvz.v1.CreateReceptionRequest\x1a\x1f.pvz.v1.CreateReceptionResponse\"\x1e\x82\xd3\xe4\x93\x02\x18b\treception\"\v/receptions\x12\x91\x01\n" +
	"\x12CloseLastReception\x12!.pvz.v1.CloseLastReceptionRequest\x1a\".pvz.v1.CloseLastReceptionResponse\"4\x82\xd3\xe4\x93\x02.b\treception\"!/pvz/{pvzId}/close_last_reception\x12h\n" +
	"\rCreateProduct\x12\x1c.pvz.v1.CreateProductRequest\x1a\x1d.pvz.v1.CreateProductResponse\"\x1a\x82\xd3\xe4\x93\x02\x14b\aproduct\"\t/products\x12\x82\x01\n" +
	"\x11DeleteLastProduct\x12 .pvz.v1.DeleteLastProductRequest\x1a!.pvz.v1.DeleteLastProductResponse\"(\x82\xd3\xe4\x93\x02\"\" /pvz/{pvzId}/delete_last_product\x12_\n" +
	"\n" +
	"DummyLogin\x12\x19.pvz.v1.DummyLoginRequest\x1a\x1a.pvz.v1.DummyLoginResponse\"\x1a\x82\xd3\xe4\x93\x02\x14b\x05token\"\v/dummyLogin\x12P\n" +
	"\bRegister\x12\x17.pvz.v1.RegisterRequest\x1a\x18.pvz.v1.RegisterResponse\"\x11\x82\xd3\xe4\x93\x02\v\"\t/register\x12K\n" +
	"\x05Login\x12\x14.pvz.v1.LoginRequest\x1a\x15.pvz.v1.LoginResponse\"\x15\x82\xd3\xe4\x93\x02\x0fb\x05token\"\x06/login\x12@\n" +
	"\n" +
	"GetPVZList\x12\x16.google.protobuf.Empty\x1a\x1a.pvz.v1.GetPVZListResponseB)Z'github.com/BlankBot-0/pvz/pvz_v1;pvz_v1b\x06proto3"

var (
	file_pvz_proto_rawDescOnce sync.Once
	file_pvz_proto_rawDescData []byte
)

func file_pvz_proto_rawDescGZIP() []byte {
	file_pvz_proto_rawDescOnce.Do(func() {
		file_pvz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pvz_proto_rawDesc), len(file_pvz_proto_rawDesc)))
	})
	return file_pvz_proto_rawDescData
}

var file_pvz_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pvz_proto_goTypes = []any{
	(*ListPVZRequest)(nil),               // 0: pvz.v1.ListPVZRequest
	(*ListPVZResponse)(nil),              // 1: pvz.v1.ListPVZResponse
	(*CreatePVZRequest)(nil),             // 2: pvz.v1.CreatePVZRequest
	(*CreatePVZResponse)(nil),            // 3: pvz.v1.CreatePVZResponse
	(*CreateReceptionRequest)(nil),       // 4: pvz.v1.CreateReceptionRequest
	(*CreateReceptionResponse)(nil),      // 5: pvz.v1.CreateReceptionResponse
	(*CloseLastReceptionRequest)(nil),    // 6: pvz.v1.CloseLastReceptionRequest
	(*CloseLastReceptionResponse)(nil),   // 7: pvz.v1.CloseLastReceptionResponse
	(*CreateProductRequest)(nil),         // 8: pvz.v1.CreateProductRequest
	(*CreateProductResponse)(nil),        // 9: pvz.v1.CreateProductResponse
	(*DeleteLastProductRequest)(nil),     // 10: pvz.v1.DeleteLastProductRequest
	(*DeleteLastProductResponse)(nil),    // 11: pvz.v1.DeleteLastProductResponse
	(*DummyLoginRequest)(nil),            // 12: pvz.v1.DummyLoginRequest
	(*DummyLoginResponse)(nil),           // 13: pvz.v1.DummyLoginResponse
	(*RegisterRequest)(nil),              // 14: pvz.v1.RegisterRequest
	(*RegisterResponse)(nil),             // 15: pvz.v1.RegisterResponse
	(*LoginRequest)(nil),                 // 16: pvz.v1.LoginRequest
	(*LoginResponse)(nil),                // 17: pvz.v1.LoginResponse
	(*GetPVZListResponse)(nil),           // 18: pvz.v1.GetPVZListResponse
	(*PVZ)(nil),                          // 19: pvz.v1.PVZ
	(*Reception)(nil),                    // 20: pvz.v1.Reception
	(*Product)(nil),                      // 21: pvz.v1.Product
	(*ListPVZResponseReceptionInfo)(nil), // 22: pvz.v1.ListPVZResponse.receptionInfo
	(*ListPVZResponsePvzInfo)(nil),       // 23: pvz.v1.ListPVZResponse.pvzInfo
	(*timestamppb.Timestamp)(nil),        // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 25: google.protobuf.Empty
}
var file_pvz_proto_depIdxs = []int32{
	24, // 0: pvz.v1.ListPVZRequest.startDate:type_name -> google.protobuf.Timestamp
	24, // 1: pvz.v1.ListPVZRequest.endDate:type_name -> google.protobuf.Timestamp
	23, // 2: pvz.v1.ListPVZResponse.pvzs:type_name -> pvz.v1.ListPVZResponse.pvzInfo
	24, // 3: pvz.v1.CreatePVZRequest.registrationDate:type_name -> google.protobuf.Timestamp
	19, // 4: pvz.v1.CreatePVZResponse.pvz:type_name -> pvz.v1.PVZ
	20, // 5: pvz.v1.CreateReceptionResponse.reception:type_name -> pvz.v1.Reception
	20, // 6: pvz.v1.CloseLastReceptionResponse.reception:type_name -> pvz.v1.Reception
	21, // 7: pvz.v1.CreateProductResponse.product:type_name -> pvz.v1.Product
	19, // 8: pvz.v1.GetPVZListResponse.pvzs:type_name -> pvz.v1.PVZ
	24, // 9: pvz.v1.PVZ.registration_date:type_name -> google.protobuf.Timestamp
	24, // 10: pvz.v1.Reception.date_time:type_name -> google.protobuf.Timestamp
	24, // 11: pvz.v1.Product.date_time:type_name -> google.protobuf.Timestamp
	20, // 12: pvz.v1.ListPVZResponse.receptionInfo.reception:type_name -> pvz.v1.Reception
	21, // 13: pvz.v1.ListPVZResponse.receptionInfo.products:type_name -> pvz.v1.Product
	19, // 14: pvz.v1.ListPVZResponse.pvzInfo.pvz:type_name -> pvz.v1.PVZ
	22, // 15: pvz.v1.ListPVZResponse.pvzInfo.receptions:type_name -> pvz.v1.ListPVZResponse.receptionInfo
	0,  // 16: pvz.v1.PVZService.ListPVZ:input_type -> pvz.v1.ListPVZRequest
	2,  // 17: pvz.v1.PVZService.CreatePVZ:input_type -> pvz.v1.CreatePVZRequest
	4,  // 18: pvz.v1.PVZService.CreateReception:input_type -> pvz.v1.CreateReceptionRequest
	6,  // 19: pvz.v1.PVZService.CloseLastReception:input_type -> pvz.v1.CloseLastReceptionRequest
	8,  // 20: pvz.v1.PVZService.CreateProduct:input_type -> pvz.v1.CreateProductRequest
	10, // 21: pvz.v1.PVZService.DeleteLastProduct:input_type -> pvz.v1.DeleteLastProductRequest
	12, // 22: pvz.v1.PVZService.DummyLogin:input_type -> pvz.v1.DummyLoginRequest
	14, // 23: pvz.v1.PVZService.Register:input_type -> pvz.v1.RegisterRequest
	16, // 24: pvz.v1.PVZService.Login:input_type -> pvz.v1.LoginRequest
	25, // 25: pvz.v1.PVZService.GetPVZList:input_type -> google.protobuf.Empty
	1,  // 26: pvz.v1.PVZService.ListPVZ:output_type -> pvz.v1.ListPVZResponse
	3,  // 27: pvz.v1.PVZService.CreatePVZ:output_type -> pvz.v1.CreatePVZResponse
	5,  // 28: pvz.v1.PVZService.CreateReception:output_type -> pvz.v1.CreateReceptionResponse
	7,  // 29: pvz.v1.PVZService.CloseLastReception:output_type -> pvz.v1.CloseLastReceptionResponse
	9,  // 30: pvz.v1.PVZService.CreateProduct:output_type -> pvz.v1.CreateProductResponse
	11, // 31: pvz.v1.PVZService.DeleteLastProduct:output_type -> pvz.v1.DeleteLastProductResponse
	13, // 32: pvz.v1.PVZService.DummyLogin:output_type -> pvz.v1.DummyLoginResponse
	15, // 33: pvz.v1.PVZService.Register:output_type -> pvz.v1.RegisterResponse
	17, // 34: pvz.v1.PVZService.Login:output_type -> pvz.v1.LoginResponse
	18, // 35: pvz.v1.PVZService.GetPVZList:output_type -> pvz.v1.GetPVZListResponse
	26, // [26:36] is the sub-list for method output_type
	16, // [16:26] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pvz_proto_init() }
func file_pvz_proto_init() {
	if File_pvz_proto != nil {
		return
	}
	file_pvz_proto_msgTypes[2].OneofWrappers = []any{}
	file_pvz_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pvz_proto_rawDesc), len(file_pvz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pvz_proto_goTypes,
		DependencyIndexes: file_pvz_proto_depIdxs,
		MessageInfos:      file_pvz_proto_msgTypes,
	}.Build()
	File_pvz_proto = out.File
	file_pvz_proto_goTypes = nil
	file_pvz_proto_depIdxs = nil
}
