// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: pvz.proto

package pvz_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PVZService_ListPVZ_FullMethodName            = "/pvz.v1.PVZService/ListPVZ"
	PVZService_CreatePVZ_FullMethodName          = "/pvz.v1.PVZService/CreatePVZ"
	PVZService_CreateReception_FullMethodName    = "/pvz.v1.PVZService/CreateReception"
	PVZService_CloseLastReception_FullMethodName = "/pvz.v1.PVZService/CloseLastReception"
	PVZService_CreateProduct_FullMethodName      = "/pvz.v1.PVZService/CreateProduct"
	PVZService_DeleteLastProduct_FullMethodName  = "/pvz.v1.PVZService/DeleteLastProduct"
	PVZService_DummyLogin_FullMethodName         = "/pvz.v1.PVZService/DummyLogin"
	PVZService_Register_FullMethodName           = "/pvz.v1.PVZService/Register"
	PVZService_Login_FullMethodName              = "/pvz.v1.PVZService/Login"
	PVZService_GetPVZList_FullMethodName         = "/pvz.v1.PVZService/ListPVZ"
)

// PVZServiceClient is the client API for PVZService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PVZServiceClient interface {
	ListPVZ(ctx context.Context, in *ListPVZRequest, opts ...grpc.CallOption) (*ListPVZResponse, error)
	CreatePVZ(ctx context.Context, in *CreatePVZRequest, opts ...grpc.CallOption) (*CreatePVZResponse, error)
	CreateReception(ctx context.Context, in *CreateReceptionRequest, opts ...grpc.CallOption) (*CreateReceptionResponse, error)
	CloseLastReception(ctx context.Context, in *CloseLastReceptionRequest, opts ...grpc.CallOption) (*CloseLastReceptionResponse, error)
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	DeleteLastProduct(ctx context.Context, in *DeleteLastProductRequest, opts ...grpc.CallOption) (*DeleteLastProductResponse, error)
	DummyLogin(ctx context.Context, in *DummyLoginRequest, opts ...grpc.CallOption) (*DummyLoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	GetPVZList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPVZListResponse, error)
}

type pVZServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPVZServiceClient(cc grpc.ClientConnInterface) PVZServiceClient {
	return &pVZServiceClient{cc}
}

func (c *pVZServiceClient) ListPVZ(ctx context.Context, in *ListPVZRequest, opts ...grpc.CallOption) (*ListPVZResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPVZResponse)
	err := c.cc.Invoke(ctx, PVZService_ListPVZ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVZServiceClient) CreatePVZ(ctx context.Context, in *CreatePVZRequest, opts ...grpc.CallOption) (*CreatePVZResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePVZResponse)
	err := c.cc.Invoke(ctx, PVZService_CreatePVZ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVZServiceClient) CreateReception(ctx context.Context, in *CreateReceptionRequest, opts ...grpc.CallOption) (*CreateReceptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReceptionResponse)
	err := c.cc.Invoke(ctx, PVZService_CreateReception_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVZServiceClient) CloseLastReception(ctx context.Context, in *CloseLastReceptionRequest, opts ...grpc.CallOption) (*CloseLastReceptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseLastReceptionResponse)
	err := c.cc.Invoke(ctx, PVZService_CloseLastReception_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVZServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, PVZService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVZServiceClient) DeleteLastProduct(ctx context.Context, in *DeleteLastProductRequest, opts ...grpc.CallOption) (*DeleteLastProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLastProductResponse)
	err := c.cc.Invoke(ctx, PVZService_DeleteLastProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVZServiceClient) DummyLogin(ctx context.Context, in *DummyLoginRequest, opts ...grpc.CallOption) (*DummyLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DummyLoginResponse)
	err := c.cc.Invoke(ctx, PVZService_DummyLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVZServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, PVZService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVZServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, PVZService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVZServiceClient) GetPVZList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPVZListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPVZListResponse)
	err := c.cc.Invoke(ctx, PVZService_GetPVZList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PVZServiceServer is the server API for PVZService service.
// All implementations must embed UnimplementedPVZServiceServer
// for forward compatibility.
type PVZServiceServer interface {
	ListPVZ(context.Context, *ListPVZRequest) (*ListPVZResponse, error)
	CreatePVZ(context.Context, *CreatePVZRequest) (*CreatePVZResponse, error)
	CreateReception(context.Context, *CreateReceptionRequest) (*CreateReceptionResponse, error)
	CloseLastReception(context.Context, *CloseLastReceptionRequest) (*CloseLastReceptionResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	DeleteLastProduct(context.Context, *DeleteLastProductRequest) (*DeleteLastProductResponse, error)
	DummyLogin(context.Context, *DummyLoginRequest) (*DummyLoginResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	GetPVZList(context.Context, *emptypb.Empty) (*GetPVZListResponse, error)
	mustEmbedUnimplementedPVZServiceServer()
}

// UnimplementedPVZServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPVZServiceServer struct{}

func (UnimplementedPVZServiceServer) ListPVZ(context.Context, *ListPVZRequest) (*ListPVZResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPVZ not implemented")
}
func (UnimplementedPVZServiceServer) CreatePVZ(context.Context, *CreatePVZRequest) (*CreatePVZResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePVZ not implemented")
}
func (UnimplementedPVZServiceServer) CreateReception(context.Context, *CreateReceptionRequest) (*CreateReceptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReception not implemented")
}
func (UnimplementedPVZServiceServer) CloseLastReception(context.Context, *CloseLastReceptionRequest) (*CloseLastReceptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseLastReception not implemented")
}
func (UnimplementedPVZServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedPVZServiceServer) DeleteLastProduct(context.Context, *DeleteLastProductRequest) (*DeleteLastProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLastProduct not implemented")
}
func (UnimplementedPVZServiceServer) DummyLogin(context.Context, *DummyLoginRequest) (*DummyLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DummyLogin not implemented")
}
func (UnimplementedPVZServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPVZServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedPVZServiceServer) GetPVZList(context.Context, *emptypb.Empty) (*GetPVZListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPVZ not implemented")
}
func (UnimplementedPVZServiceServer) mustEmbedUnimplementedPVZServiceServer() {}
func (UnimplementedPVZServiceServer) testEmbeddedByValue()                    {}

// UnsafePVZServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PVZServiceServer will
// result in compilation errors.
type UnsafePVZServiceServer interface {
	mustEmbedUnimplementedPVZServiceServer()
}

func RegisterPVZServiceServer(s grpc.ServiceRegistrar, srv PVZServiceServer) {
	// If the following call pancis, it indicates UnimplementedPVZServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PVZService_ServiceDesc, srv)
}

func _PVZService_ListPVZ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPVZRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVZServiceServer).ListPVZ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PVZService_ListPVZ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVZServiceServer).ListPVZ(ctx, req.(*ListPVZRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVZService_CreatePVZ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePVZRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVZServiceServer).CreatePVZ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PVZService_CreatePVZ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVZServiceServer).CreatePVZ(ctx, req.(*CreatePVZRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVZService_CreateReception_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReceptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVZServiceServer).CreateReception(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PVZService_CreateReception_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVZServiceServer).CreateReception(ctx, req.(*CreateReceptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVZService_CloseLastReception_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseLastReceptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVZServiceServer).CloseLastReception(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PVZService_CloseLastReception_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVZServiceServer).CloseLastReception(ctx, req.(*CloseLastReceptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVZService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVZServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PVZService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVZServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVZService_DeleteLastProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLastProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVZServiceServer).DeleteLastProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PVZService_DeleteLastProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVZServiceServer).DeleteLastProduct(ctx, req.(*DeleteLastProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVZService_DummyLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DummyLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVZServiceServer).DummyLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PVZService_DummyLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVZServiceServer).DummyLogin(ctx, req.(*DummyLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVZService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVZServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PVZService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVZServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVZService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVZServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PVZService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVZServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVZService_GetPVZList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVZServiceServer).GetPVZList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PVZService_GetPVZList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVZServiceServer).GetPVZList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PVZService_ServiceDesc is the grpc.ServiceDesc for PVZService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PVZService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pvz.v1.PVZService",
	HandlerType: (*PVZServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPVZ",
			Handler:    _PVZService_ListPVZ_Handler,
		},
		{
			MethodName: "CreatePVZ",
			Handler:    _PVZService_CreatePVZ_Handler,
		},
		{
			MethodName: "CreateReception",
			Handler:    _PVZService_CreateReception_Handler,
		},
		{
			MethodName: "CloseLastReception",
			Handler:    _PVZService_CloseLastReception_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _PVZService_CreateProduct_Handler,
		},
		{
			MethodName: "DeleteLastProduct",
			Handler:    _PVZService_DeleteLastProduct_Handler,
		},
		{
			MethodName: "DummyLogin",
			Handler:    _PVZService_DummyLogin_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _PVZService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _PVZService_Login_Handler,
		},
		{
			MethodName: "ListPVZ",
			Handler:    _PVZService_GetPVZList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pvz.proto",
}
