// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i pvz/internal/postgres.RWUsers -o user_mock.go -n UserMock -p mocks

import (
	"context"
	"pvz/internal/models"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UserMock implements mm_postgres.RWUsers
type UserMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateUser          func(ctx context.Context, email string, passwordHash string, role string) (s1 string, err error)
	funcCreateUserOrigin    string
	inspectFuncCreateUser   func(ctx context.Context, email string, passwordHash string, role string)
	afterCreateUserCounter  uint64
	beforeCreateUserCounter uint64
	CreateUserMock          mUserMockCreateUser

	funcUserByEmail          func(ctx context.Context, email string) (u1 models.User, err error)
	funcUserByEmailOrigin    string
	inspectFuncUserByEmail   func(ctx context.Context, email string)
	afterUserByEmailCounter  uint64
	beforeUserByEmailCounter uint64
	UserByEmailMock          mUserMockUserByEmail

	funcUserByID          func(ctx context.Context, userId string) (u1 models.User, err error)
	funcUserByIDOrigin    string
	inspectFuncUserByID   func(ctx context.Context, userId string)
	afterUserByIDCounter  uint64
	beforeUserByIDCounter uint64
	UserByIDMock          mUserMockUserByID

	funcValidateRole          func(ctx context.Context, role string) (err error)
	funcValidateRoleOrigin    string
	inspectFuncValidateRole   func(ctx context.Context, role string)
	afterValidateRoleCounter  uint64
	beforeValidateRoleCounter uint64
	ValidateRoleMock          mUserMockValidateRole
}

// NewUserMock returns a mock for mm_postgres.RWUsers
func NewUserMock(t minimock.Tester) *UserMock {
	m := &UserMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateUserMock = mUserMockCreateUser{mock: m}
	m.CreateUserMock.callArgs = []*UserMockCreateUserParams{}

	m.UserByEmailMock = mUserMockUserByEmail{mock: m}
	m.UserByEmailMock.callArgs = []*UserMockUserByEmailParams{}

	m.UserByIDMock = mUserMockUserByID{mock: m}
	m.UserByIDMock.callArgs = []*UserMockUserByIDParams{}

	m.ValidateRoleMock = mUserMockValidateRole{mock: m}
	m.ValidateRoleMock.callArgs = []*UserMockValidateRoleParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserMockCreateUser struct {
	optional           bool
	mock               *UserMock
	defaultExpectation *UserMockCreateUserExpectation
	expectations       []*UserMockCreateUserExpectation

	callArgs []*UserMockCreateUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserMockCreateUserExpectation specifies expectation struct of the RWUsers.CreateUser
type UserMockCreateUserExpectation struct {
	mock               *UserMock
	params             *UserMockCreateUserParams
	paramPtrs          *UserMockCreateUserParamPtrs
	expectationOrigins UserMockCreateUserExpectationOrigins
	results            *UserMockCreateUserResults
	returnOrigin       string
	Counter            uint64
}

// UserMockCreateUserParams contains parameters of the RWUsers.CreateUser
type UserMockCreateUserParams struct {
	ctx          context.Context
	email        string
	passwordHash string
	role         string
}

// UserMockCreateUserParamPtrs contains pointers to parameters of the RWUsers.CreateUser
type UserMockCreateUserParamPtrs struct {
	ctx          *context.Context
	email        *string
	passwordHash *string
	role         *string
}

// UserMockCreateUserResults contains results of the RWUsers.CreateUser
type UserMockCreateUserResults struct {
	s1  string
	err error
}

// UserMockCreateUserOrigins contains origins of expectations of the RWUsers.CreateUser
type UserMockCreateUserExpectationOrigins struct {
	origin             string
	originCtx          string
	originEmail        string
	originPasswordHash string
	originRole         string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateUser *mUserMockCreateUser) Optional() *mUserMockCreateUser {
	mmCreateUser.optional = true
	return mmCreateUser
}

// Expect sets up expected params for RWUsers.CreateUser
func (mmCreateUser *mUserMockCreateUser) Expect(ctx context.Context, email string, passwordHash string, role string) *mUserMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("UserMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &UserMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.paramPtrs != nil {
		mmCreateUser.mock.t.Fatalf("UserMock.CreateUser mock is already set by ExpectParams functions")
	}

	mmCreateUser.defaultExpectation.params = &UserMockCreateUserParams{ctx, email, passwordHash, role}
	mmCreateUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateUser.expectations {
		if minimock.Equal(e.params, mmCreateUser.defaultExpectation.params) {
			mmCreateUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateUser.defaultExpectation.params)
		}
	}

	return mmCreateUser
}

// ExpectCtxParam1 sets up expected param ctx for RWUsers.CreateUser
func (mmCreateUser *mUserMockCreateUser) ExpectCtxParam1(ctx context.Context) *mUserMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("UserMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &UserMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.params != nil {
		mmCreateUser.mock.t.Fatalf("UserMock.CreateUser mock is already set by Expect")
	}

	if mmCreateUser.defaultExpectation.paramPtrs == nil {
		mmCreateUser.defaultExpectation.paramPtrs = &UserMockCreateUserParamPtrs{}
	}
	mmCreateUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateUser
}

// ExpectEmailParam2 sets up expected param email for RWUsers.CreateUser
func (mmCreateUser *mUserMockCreateUser) ExpectEmailParam2(email string) *mUserMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("UserMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &UserMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.params != nil {
		mmCreateUser.mock.t.Fatalf("UserMock.CreateUser mock is already set by Expect")
	}

	if mmCreateUser.defaultExpectation.paramPtrs == nil {
		mmCreateUser.defaultExpectation.paramPtrs = &UserMockCreateUserParamPtrs{}
	}
	mmCreateUser.defaultExpectation.paramPtrs.email = &email
	mmCreateUser.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmCreateUser
}

// ExpectPasswordHashParam3 sets up expected param passwordHash for RWUsers.CreateUser
func (mmCreateUser *mUserMockCreateUser) ExpectPasswordHashParam3(passwordHash string) *mUserMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("UserMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &UserMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.params != nil {
		mmCreateUser.mock.t.Fatalf("UserMock.CreateUser mock is already set by Expect")
	}

	if mmCreateUser.defaultExpectation.paramPtrs == nil {
		mmCreateUser.defaultExpectation.paramPtrs = &UserMockCreateUserParamPtrs{}
	}
	mmCreateUser.defaultExpectation.paramPtrs.passwordHash = &passwordHash
	mmCreateUser.defaultExpectation.expectationOrigins.originPasswordHash = minimock.CallerInfo(1)

	return mmCreateUser
}

// ExpectRoleParam4 sets up expected param role for RWUsers.CreateUser
func (mmCreateUser *mUserMockCreateUser) ExpectRoleParam4(role string) *mUserMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("UserMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &UserMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.params != nil {
		mmCreateUser.mock.t.Fatalf("UserMock.CreateUser mock is already set by Expect")
	}

	if mmCreateUser.defaultExpectation.paramPtrs == nil {
		mmCreateUser.defaultExpectation.paramPtrs = &UserMockCreateUserParamPtrs{}
	}
	mmCreateUser.defaultExpectation.paramPtrs.role = &role
	mmCreateUser.defaultExpectation.expectationOrigins.originRole = minimock.CallerInfo(1)

	return mmCreateUser
}

// Inspect accepts an inspector function that has same arguments as the RWUsers.CreateUser
func (mmCreateUser *mUserMockCreateUser) Inspect(f func(ctx context.Context, email string, passwordHash string, role string)) *mUserMockCreateUser {
	if mmCreateUser.mock.inspectFuncCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("Inspect function is already set for UserMock.CreateUser")
	}

	mmCreateUser.mock.inspectFuncCreateUser = f

	return mmCreateUser
}

// Return sets up results that will be returned by RWUsers.CreateUser
func (mmCreateUser *mUserMockCreateUser) Return(s1 string, err error) *UserMock {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("UserMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &UserMockCreateUserExpectation{mock: mmCreateUser.mock}
	}
	mmCreateUser.defaultExpectation.results = &UserMockCreateUserResults{s1, err}
	mmCreateUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateUser.mock
}

// Set uses given function f to mock the RWUsers.CreateUser method
func (mmCreateUser *mUserMockCreateUser) Set(f func(ctx context.Context, email string, passwordHash string, role string) (s1 string, err error)) *UserMock {
	if mmCreateUser.defaultExpectation != nil {
		mmCreateUser.mock.t.Fatalf("Default expectation is already set for the RWUsers.CreateUser method")
	}

	if len(mmCreateUser.expectations) > 0 {
		mmCreateUser.mock.t.Fatalf("Some expectations are already set for the RWUsers.CreateUser method")
	}

	mmCreateUser.mock.funcCreateUser = f
	mmCreateUser.mock.funcCreateUserOrigin = minimock.CallerInfo(1)
	return mmCreateUser.mock
}

// When sets expectation for the RWUsers.CreateUser which will trigger the result defined by the following
// Then helper
func (mmCreateUser *mUserMockCreateUser) When(ctx context.Context, email string, passwordHash string, role string) *UserMockCreateUserExpectation {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("UserMock.CreateUser mock is already set by Set")
	}

	expectation := &UserMockCreateUserExpectation{
		mock:               mmCreateUser.mock,
		params:             &UserMockCreateUserParams{ctx, email, passwordHash, role},
		expectationOrigins: UserMockCreateUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateUser.expectations = append(mmCreateUser.expectations, expectation)
	return expectation
}

// Then sets up RWUsers.CreateUser return parameters for the expectation previously defined by the When method
func (e *UserMockCreateUserExpectation) Then(s1 string, err error) *UserMock {
	e.results = &UserMockCreateUserResults{s1, err}
	return e.mock
}

// Times sets number of times RWUsers.CreateUser should be invoked
func (mmCreateUser *mUserMockCreateUser) Times(n uint64) *mUserMockCreateUser {
	if n == 0 {
		mmCreateUser.mock.t.Fatalf("Times of UserMock.CreateUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateUser.expectedInvocations, n)
	mmCreateUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateUser
}

func (mmCreateUser *mUserMockCreateUser) invocationsDone() bool {
	if len(mmCreateUser.expectations) == 0 && mmCreateUser.defaultExpectation == nil && mmCreateUser.mock.funcCreateUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateUser.mock.afterCreateUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateUser implements mm_postgres.RWUsers
func (mmCreateUser *UserMock) CreateUser(ctx context.Context, email string, passwordHash string, role string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmCreateUser.beforeCreateUserCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateUser.afterCreateUserCounter, 1)

	mmCreateUser.t.Helper()

	if mmCreateUser.inspectFuncCreateUser != nil {
		mmCreateUser.inspectFuncCreateUser(ctx, email, passwordHash, role)
	}

	mm_params := UserMockCreateUserParams{ctx, email, passwordHash, role}

	// Record call args
	mmCreateUser.CreateUserMock.mutex.Lock()
	mmCreateUser.CreateUserMock.callArgs = append(mmCreateUser.CreateUserMock.callArgs, &mm_params)
	mmCreateUser.CreateUserMock.mutex.Unlock()

	for _, e := range mmCreateUser.CreateUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmCreateUser.CreateUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateUser.CreateUserMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateUser.CreateUserMock.defaultExpectation.params
		mm_want_ptrs := mmCreateUser.CreateUserMock.defaultExpectation.paramPtrs

		mm_got := UserMockCreateUserParams{ctx, email, passwordHash, role}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateUser.t.Errorf("UserMock.CreateUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmCreateUser.t.Errorf("UserMock.CreateUser got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

			if mm_want_ptrs.passwordHash != nil && !minimock.Equal(*mm_want_ptrs.passwordHash, mm_got.passwordHash) {
				mmCreateUser.t.Errorf("UserMock.CreateUser got unexpected parameter passwordHash, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.originPasswordHash, *mm_want_ptrs.passwordHash, mm_got.passwordHash, minimock.Diff(*mm_want_ptrs.passwordHash, mm_got.passwordHash))
			}

			if mm_want_ptrs.role != nil && !minimock.Equal(*mm_want_ptrs.role, mm_got.role) {
				mmCreateUser.t.Errorf("UserMock.CreateUser got unexpected parameter role, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.originRole, *mm_want_ptrs.role, mm_got.role, minimock.Diff(*mm_want_ptrs.role, mm_got.role))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateUser.t.Errorf("UserMock.CreateUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateUser.CreateUserMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateUser.t.Fatal("No results are set for the UserMock.CreateUser")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmCreateUser.funcCreateUser != nil {
		return mmCreateUser.funcCreateUser(ctx, email, passwordHash, role)
	}
	mmCreateUser.t.Fatalf("Unexpected call to UserMock.CreateUser. %v %v %v %v", ctx, email, passwordHash, role)
	return
}

// CreateUserAfterCounter returns a count of finished UserMock.CreateUser invocations
func (mmCreateUser *UserMock) CreateUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateUser.afterCreateUserCounter)
}

// CreateUserBeforeCounter returns a count of UserMock.CreateUser invocations
func (mmCreateUser *UserMock) CreateUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateUser.beforeCreateUserCounter)
}

// Calls returns a list of arguments used in each call to UserMock.CreateUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateUser *mUserMockCreateUser) Calls() []*UserMockCreateUserParams {
	mmCreateUser.mutex.RLock()

	argCopy := make([]*UserMockCreateUserParams, len(mmCreateUser.callArgs))
	copy(argCopy, mmCreateUser.callArgs)

	mmCreateUser.mutex.RUnlock()

	return argCopy
}

// MinimockCreateUserDone returns true if the count of the CreateUser invocations corresponds
// the number of defined expectations
func (m *UserMock) MinimockCreateUserDone() bool {
	if m.CreateUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateUserMock.invocationsDone()
}

// MinimockCreateUserInspect logs each unmet expectation
func (m *UserMock) MinimockCreateUserInspect() {
	for _, e := range m.CreateUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserMock.CreateUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateUserCounter := mm_atomic.LoadUint64(&m.afterCreateUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateUserMock.defaultExpectation != nil && afterCreateUserCounter < 1 {
		if m.CreateUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserMock.CreateUser at\n%s", m.CreateUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserMock.CreateUser at\n%s with params: %#v", m.CreateUserMock.defaultExpectation.expectationOrigins.origin, *m.CreateUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateUser != nil && afterCreateUserCounter < 1 {
		m.t.Errorf("Expected call to UserMock.CreateUser at\n%s", m.funcCreateUserOrigin)
	}

	if !m.CreateUserMock.invocationsDone() && afterCreateUserCounter > 0 {
		m.t.Errorf("Expected %d calls to UserMock.CreateUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateUserMock.expectedInvocations), m.CreateUserMock.expectedInvocationsOrigin, afterCreateUserCounter)
	}
}

type mUserMockUserByEmail struct {
	optional           bool
	mock               *UserMock
	defaultExpectation *UserMockUserByEmailExpectation
	expectations       []*UserMockUserByEmailExpectation

	callArgs []*UserMockUserByEmailParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserMockUserByEmailExpectation specifies expectation struct of the RWUsers.UserByEmail
type UserMockUserByEmailExpectation struct {
	mock               *UserMock
	params             *UserMockUserByEmailParams
	paramPtrs          *UserMockUserByEmailParamPtrs
	expectationOrigins UserMockUserByEmailExpectationOrigins
	results            *UserMockUserByEmailResults
	returnOrigin       string
	Counter            uint64
}

// UserMockUserByEmailParams contains parameters of the RWUsers.UserByEmail
type UserMockUserByEmailParams struct {
	ctx   context.Context
	email string
}

// UserMockUserByEmailParamPtrs contains pointers to parameters of the RWUsers.UserByEmail
type UserMockUserByEmailParamPtrs struct {
	ctx   *context.Context
	email *string
}

// UserMockUserByEmailResults contains results of the RWUsers.UserByEmail
type UserMockUserByEmailResults struct {
	u1  models.User
	err error
}

// UserMockUserByEmailOrigins contains origins of expectations of the RWUsers.UserByEmail
type UserMockUserByEmailExpectationOrigins struct {
	origin      string
	originCtx   string
	originEmail string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUserByEmail *mUserMockUserByEmail) Optional() *mUserMockUserByEmail {
	mmUserByEmail.optional = true
	return mmUserByEmail
}

// Expect sets up expected params for RWUsers.UserByEmail
func (mmUserByEmail *mUserMockUserByEmail) Expect(ctx context.Context, email string) *mUserMockUserByEmail {
	if mmUserByEmail.mock.funcUserByEmail != nil {
		mmUserByEmail.mock.t.Fatalf("UserMock.UserByEmail mock is already set by Set")
	}

	if mmUserByEmail.defaultExpectation == nil {
		mmUserByEmail.defaultExpectation = &UserMockUserByEmailExpectation{}
	}

	if mmUserByEmail.defaultExpectation.paramPtrs != nil {
		mmUserByEmail.mock.t.Fatalf("UserMock.UserByEmail mock is already set by ExpectParams functions")
	}

	mmUserByEmail.defaultExpectation.params = &UserMockUserByEmailParams{ctx, email}
	mmUserByEmail.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUserByEmail.expectations {
		if minimock.Equal(e.params, mmUserByEmail.defaultExpectation.params) {
			mmUserByEmail.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUserByEmail.defaultExpectation.params)
		}
	}

	return mmUserByEmail
}

// ExpectCtxParam1 sets up expected param ctx for RWUsers.UserByEmail
func (mmUserByEmail *mUserMockUserByEmail) ExpectCtxParam1(ctx context.Context) *mUserMockUserByEmail {
	if mmUserByEmail.mock.funcUserByEmail != nil {
		mmUserByEmail.mock.t.Fatalf("UserMock.UserByEmail mock is already set by Set")
	}

	if mmUserByEmail.defaultExpectation == nil {
		mmUserByEmail.defaultExpectation = &UserMockUserByEmailExpectation{}
	}

	if mmUserByEmail.defaultExpectation.params != nil {
		mmUserByEmail.mock.t.Fatalf("UserMock.UserByEmail mock is already set by Expect")
	}

	if mmUserByEmail.defaultExpectation.paramPtrs == nil {
		mmUserByEmail.defaultExpectation.paramPtrs = &UserMockUserByEmailParamPtrs{}
	}
	mmUserByEmail.defaultExpectation.paramPtrs.ctx = &ctx
	mmUserByEmail.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUserByEmail
}

// ExpectEmailParam2 sets up expected param email for RWUsers.UserByEmail
func (mmUserByEmail *mUserMockUserByEmail) ExpectEmailParam2(email string) *mUserMockUserByEmail {
	if mmUserByEmail.mock.funcUserByEmail != nil {
		mmUserByEmail.mock.t.Fatalf("UserMock.UserByEmail mock is already set by Set")
	}

	if mmUserByEmail.defaultExpectation == nil {
		mmUserByEmail.defaultExpectation = &UserMockUserByEmailExpectation{}
	}

	if mmUserByEmail.defaultExpectation.params != nil {
		mmUserByEmail.mock.t.Fatalf("UserMock.UserByEmail mock is already set by Expect")
	}

	if mmUserByEmail.defaultExpectation.paramPtrs == nil {
		mmUserByEmail.defaultExpectation.paramPtrs = &UserMockUserByEmailParamPtrs{}
	}
	mmUserByEmail.defaultExpectation.paramPtrs.email = &email
	mmUserByEmail.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmUserByEmail
}

// Inspect accepts an inspector function that has same arguments as the RWUsers.UserByEmail
func (mmUserByEmail *mUserMockUserByEmail) Inspect(f func(ctx context.Context, email string)) *mUserMockUserByEmail {
	if mmUserByEmail.mock.inspectFuncUserByEmail != nil {
		mmUserByEmail.mock.t.Fatalf("Inspect function is already set for UserMock.UserByEmail")
	}

	mmUserByEmail.mock.inspectFuncUserByEmail = f

	return mmUserByEmail
}

// Return sets up results that will be returned by RWUsers.UserByEmail
func (mmUserByEmail *mUserMockUserByEmail) Return(u1 models.User, err error) *UserMock {
	if mmUserByEmail.mock.funcUserByEmail != nil {
		mmUserByEmail.mock.t.Fatalf("UserMock.UserByEmail mock is already set by Set")
	}

	if mmUserByEmail.defaultExpectation == nil {
		mmUserByEmail.defaultExpectation = &UserMockUserByEmailExpectation{mock: mmUserByEmail.mock}
	}
	mmUserByEmail.defaultExpectation.results = &UserMockUserByEmailResults{u1, err}
	mmUserByEmail.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUserByEmail.mock
}

// Set uses given function f to mock the RWUsers.UserByEmail method
func (mmUserByEmail *mUserMockUserByEmail) Set(f func(ctx context.Context, email string) (u1 models.User, err error)) *UserMock {
	if mmUserByEmail.defaultExpectation != nil {
		mmUserByEmail.mock.t.Fatalf("Default expectation is already set for the RWUsers.UserByEmail method")
	}

	if len(mmUserByEmail.expectations) > 0 {
		mmUserByEmail.mock.t.Fatalf("Some expectations are already set for the RWUsers.UserByEmail method")
	}

	mmUserByEmail.mock.funcUserByEmail = f
	mmUserByEmail.mock.funcUserByEmailOrigin = minimock.CallerInfo(1)
	return mmUserByEmail.mock
}

// When sets expectation for the RWUsers.UserByEmail which will trigger the result defined by the following
// Then helper
func (mmUserByEmail *mUserMockUserByEmail) When(ctx context.Context, email string) *UserMockUserByEmailExpectation {
	if mmUserByEmail.mock.funcUserByEmail != nil {
		mmUserByEmail.mock.t.Fatalf("UserMock.UserByEmail mock is already set by Set")
	}

	expectation := &UserMockUserByEmailExpectation{
		mock:               mmUserByEmail.mock,
		params:             &UserMockUserByEmailParams{ctx, email},
		expectationOrigins: UserMockUserByEmailExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUserByEmail.expectations = append(mmUserByEmail.expectations, expectation)
	return expectation
}

// Then sets up RWUsers.UserByEmail return parameters for the expectation previously defined by the When method
func (e *UserMockUserByEmailExpectation) Then(u1 models.User, err error) *UserMock {
	e.results = &UserMockUserByEmailResults{u1, err}
	return e.mock
}

// Times sets number of times RWUsers.UserByEmail should be invoked
func (mmUserByEmail *mUserMockUserByEmail) Times(n uint64) *mUserMockUserByEmail {
	if n == 0 {
		mmUserByEmail.mock.t.Fatalf("Times of UserMock.UserByEmail mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUserByEmail.expectedInvocations, n)
	mmUserByEmail.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUserByEmail
}

func (mmUserByEmail *mUserMockUserByEmail) invocationsDone() bool {
	if len(mmUserByEmail.expectations) == 0 && mmUserByEmail.defaultExpectation == nil && mmUserByEmail.mock.funcUserByEmail == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUserByEmail.mock.afterUserByEmailCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUserByEmail.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UserByEmail implements mm_postgres.RWUsers
func (mmUserByEmail *UserMock) UserByEmail(ctx context.Context, email string) (u1 models.User, err error) {
	mm_atomic.AddUint64(&mmUserByEmail.beforeUserByEmailCounter, 1)
	defer mm_atomic.AddUint64(&mmUserByEmail.afterUserByEmailCounter, 1)

	mmUserByEmail.t.Helper()

	if mmUserByEmail.inspectFuncUserByEmail != nil {
		mmUserByEmail.inspectFuncUserByEmail(ctx, email)
	}

	mm_params := UserMockUserByEmailParams{ctx, email}

	// Record call args
	mmUserByEmail.UserByEmailMock.mutex.Lock()
	mmUserByEmail.UserByEmailMock.callArgs = append(mmUserByEmail.UserByEmailMock.callArgs, &mm_params)
	mmUserByEmail.UserByEmailMock.mutex.Unlock()

	for _, e := range mmUserByEmail.UserByEmailMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmUserByEmail.UserByEmailMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUserByEmail.UserByEmailMock.defaultExpectation.Counter, 1)
		mm_want := mmUserByEmail.UserByEmailMock.defaultExpectation.params
		mm_want_ptrs := mmUserByEmail.UserByEmailMock.defaultExpectation.paramPtrs

		mm_got := UserMockUserByEmailParams{ctx, email}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUserByEmail.t.Errorf("UserMock.UserByEmail got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUserByEmail.UserByEmailMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmUserByEmail.t.Errorf("UserMock.UserByEmail got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUserByEmail.UserByEmailMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUserByEmail.t.Errorf("UserMock.UserByEmail got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUserByEmail.UserByEmailMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUserByEmail.UserByEmailMock.defaultExpectation.results
		if mm_results == nil {
			mmUserByEmail.t.Fatal("No results are set for the UserMock.UserByEmail")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmUserByEmail.funcUserByEmail != nil {
		return mmUserByEmail.funcUserByEmail(ctx, email)
	}
	mmUserByEmail.t.Fatalf("Unexpected call to UserMock.UserByEmail. %v %v", ctx, email)
	return
}

// UserByEmailAfterCounter returns a count of finished UserMock.UserByEmail invocations
func (mmUserByEmail *UserMock) UserByEmailAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUserByEmail.afterUserByEmailCounter)
}

// UserByEmailBeforeCounter returns a count of UserMock.UserByEmail invocations
func (mmUserByEmail *UserMock) UserByEmailBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUserByEmail.beforeUserByEmailCounter)
}

// Calls returns a list of arguments used in each call to UserMock.UserByEmail.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUserByEmail *mUserMockUserByEmail) Calls() []*UserMockUserByEmailParams {
	mmUserByEmail.mutex.RLock()

	argCopy := make([]*UserMockUserByEmailParams, len(mmUserByEmail.callArgs))
	copy(argCopy, mmUserByEmail.callArgs)

	mmUserByEmail.mutex.RUnlock()

	return argCopy
}

// MinimockUserByEmailDone returns true if the count of the UserByEmail invocations corresponds
// the number of defined expectations
func (m *UserMock) MinimockUserByEmailDone() bool {
	if m.UserByEmailMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UserByEmailMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UserByEmailMock.invocationsDone()
}

// MinimockUserByEmailInspect logs each unmet expectation
func (m *UserMock) MinimockUserByEmailInspect() {
	for _, e := range m.UserByEmailMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserMock.UserByEmail at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUserByEmailCounter := mm_atomic.LoadUint64(&m.afterUserByEmailCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UserByEmailMock.defaultExpectation != nil && afterUserByEmailCounter < 1 {
		if m.UserByEmailMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserMock.UserByEmail at\n%s", m.UserByEmailMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserMock.UserByEmail at\n%s with params: %#v", m.UserByEmailMock.defaultExpectation.expectationOrigins.origin, *m.UserByEmailMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUserByEmail != nil && afterUserByEmailCounter < 1 {
		m.t.Errorf("Expected call to UserMock.UserByEmail at\n%s", m.funcUserByEmailOrigin)
	}

	if !m.UserByEmailMock.invocationsDone() && afterUserByEmailCounter > 0 {
		m.t.Errorf("Expected %d calls to UserMock.UserByEmail at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UserByEmailMock.expectedInvocations), m.UserByEmailMock.expectedInvocationsOrigin, afterUserByEmailCounter)
	}
}

type mUserMockUserByID struct {
	optional           bool
	mock               *UserMock
	defaultExpectation *UserMockUserByIDExpectation
	expectations       []*UserMockUserByIDExpectation

	callArgs []*UserMockUserByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserMockUserByIDExpectation specifies expectation struct of the RWUsers.UserByID
type UserMockUserByIDExpectation struct {
	mock               *UserMock
	params             *UserMockUserByIDParams
	paramPtrs          *UserMockUserByIDParamPtrs
	expectationOrigins UserMockUserByIDExpectationOrigins
	results            *UserMockUserByIDResults
	returnOrigin       string
	Counter            uint64
}

// UserMockUserByIDParams contains parameters of the RWUsers.UserByID
type UserMockUserByIDParams struct {
	ctx    context.Context
	userId string
}

// UserMockUserByIDParamPtrs contains pointers to parameters of the RWUsers.UserByID
type UserMockUserByIDParamPtrs struct {
	ctx    *context.Context
	userId *string
}

// UserMockUserByIDResults contains results of the RWUsers.UserByID
type UserMockUserByIDResults struct {
	u1  models.User
	err error
}

// UserMockUserByIDOrigins contains origins of expectations of the RWUsers.UserByID
type UserMockUserByIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUserByID *mUserMockUserByID) Optional() *mUserMockUserByID {
	mmUserByID.optional = true
	return mmUserByID
}

// Expect sets up expected params for RWUsers.UserByID
func (mmUserByID *mUserMockUserByID) Expect(ctx context.Context, userId string) *mUserMockUserByID {
	if mmUserByID.mock.funcUserByID != nil {
		mmUserByID.mock.t.Fatalf("UserMock.UserByID mock is already set by Set")
	}

	if mmUserByID.defaultExpectation == nil {
		mmUserByID.defaultExpectation = &UserMockUserByIDExpectation{}
	}

	if mmUserByID.defaultExpectation.paramPtrs != nil {
		mmUserByID.mock.t.Fatalf("UserMock.UserByID mock is already set by ExpectParams functions")
	}

	mmUserByID.defaultExpectation.params = &UserMockUserByIDParams{ctx, userId}
	mmUserByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUserByID.expectations {
		if minimock.Equal(e.params, mmUserByID.defaultExpectation.params) {
			mmUserByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUserByID.defaultExpectation.params)
		}
	}

	return mmUserByID
}

// ExpectCtxParam1 sets up expected param ctx for RWUsers.UserByID
func (mmUserByID *mUserMockUserByID) ExpectCtxParam1(ctx context.Context) *mUserMockUserByID {
	if mmUserByID.mock.funcUserByID != nil {
		mmUserByID.mock.t.Fatalf("UserMock.UserByID mock is already set by Set")
	}

	if mmUserByID.defaultExpectation == nil {
		mmUserByID.defaultExpectation = &UserMockUserByIDExpectation{}
	}

	if mmUserByID.defaultExpectation.params != nil {
		mmUserByID.mock.t.Fatalf("UserMock.UserByID mock is already set by Expect")
	}

	if mmUserByID.defaultExpectation.paramPtrs == nil {
		mmUserByID.defaultExpectation.paramPtrs = &UserMockUserByIDParamPtrs{}
	}
	mmUserByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmUserByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUserByID
}

// ExpectUserIdParam2 sets up expected param userId for RWUsers.UserByID
func (mmUserByID *mUserMockUserByID) ExpectUserIdParam2(userId string) *mUserMockUserByID {
	if mmUserByID.mock.funcUserByID != nil {
		mmUserByID.mock.t.Fatalf("UserMock.UserByID mock is already set by Set")
	}

	if mmUserByID.defaultExpectation == nil {
		mmUserByID.defaultExpectation = &UserMockUserByIDExpectation{}
	}

	if mmUserByID.defaultExpectation.params != nil {
		mmUserByID.mock.t.Fatalf("UserMock.UserByID mock is already set by Expect")
	}

	if mmUserByID.defaultExpectation.paramPtrs == nil {
		mmUserByID.defaultExpectation.paramPtrs = &UserMockUserByIDParamPtrs{}
	}
	mmUserByID.defaultExpectation.paramPtrs.userId = &userId
	mmUserByID.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmUserByID
}

// Inspect accepts an inspector function that has same arguments as the RWUsers.UserByID
func (mmUserByID *mUserMockUserByID) Inspect(f func(ctx context.Context, userId string)) *mUserMockUserByID {
	if mmUserByID.mock.inspectFuncUserByID != nil {
		mmUserByID.mock.t.Fatalf("Inspect function is already set for UserMock.UserByID")
	}

	mmUserByID.mock.inspectFuncUserByID = f

	return mmUserByID
}

// Return sets up results that will be returned by RWUsers.UserByID
func (mmUserByID *mUserMockUserByID) Return(u1 models.User, err error) *UserMock {
	if mmUserByID.mock.funcUserByID != nil {
		mmUserByID.mock.t.Fatalf("UserMock.UserByID mock is already set by Set")
	}

	if mmUserByID.defaultExpectation == nil {
		mmUserByID.defaultExpectation = &UserMockUserByIDExpectation{mock: mmUserByID.mock}
	}
	mmUserByID.defaultExpectation.results = &UserMockUserByIDResults{u1, err}
	mmUserByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUserByID.mock
}

// Set uses given function f to mock the RWUsers.UserByID method
func (mmUserByID *mUserMockUserByID) Set(f func(ctx context.Context, userId string) (u1 models.User, err error)) *UserMock {
	if mmUserByID.defaultExpectation != nil {
		mmUserByID.mock.t.Fatalf("Default expectation is already set for the RWUsers.UserByID method")
	}

	if len(mmUserByID.expectations) > 0 {
		mmUserByID.mock.t.Fatalf("Some expectations are already set for the RWUsers.UserByID method")
	}

	mmUserByID.mock.funcUserByID = f
	mmUserByID.mock.funcUserByIDOrigin = minimock.CallerInfo(1)
	return mmUserByID.mock
}

// When sets expectation for the RWUsers.UserByID which will trigger the result defined by the following
// Then helper
func (mmUserByID *mUserMockUserByID) When(ctx context.Context, userId string) *UserMockUserByIDExpectation {
	if mmUserByID.mock.funcUserByID != nil {
		mmUserByID.mock.t.Fatalf("UserMock.UserByID mock is already set by Set")
	}

	expectation := &UserMockUserByIDExpectation{
		mock:               mmUserByID.mock,
		params:             &UserMockUserByIDParams{ctx, userId},
		expectationOrigins: UserMockUserByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUserByID.expectations = append(mmUserByID.expectations, expectation)
	return expectation
}

// Then sets up RWUsers.UserByID return parameters for the expectation previously defined by the When method
func (e *UserMockUserByIDExpectation) Then(u1 models.User, err error) *UserMock {
	e.results = &UserMockUserByIDResults{u1, err}
	return e.mock
}

// Times sets number of times RWUsers.UserByID should be invoked
func (mmUserByID *mUserMockUserByID) Times(n uint64) *mUserMockUserByID {
	if n == 0 {
		mmUserByID.mock.t.Fatalf("Times of UserMock.UserByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUserByID.expectedInvocations, n)
	mmUserByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUserByID
}

func (mmUserByID *mUserMockUserByID) invocationsDone() bool {
	if len(mmUserByID.expectations) == 0 && mmUserByID.defaultExpectation == nil && mmUserByID.mock.funcUserByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUserByID.mock.afterUserByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUserByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UserByID implements mm_postgres.RWUsers
func (mmUserByID *UserMock) UserByID(ctx context.Context, userId string) (u1 models.User, err error) {
	mm_atomic.AddUint64(&mmUserByID.beforeUserByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmUserByID.afterUserByIDCounter, 1)

	mmUserByID.t.Helper()

	if mmUserByID.inspectFuncUserByID != nil {
		mmUserByID.inspectFuncUserByID(ctx, userId)
	}

	mm_params := UserMockUserByIDParams{ctx, userId}

	// Record call args
	mmUserByID.UserByIDMock.mutex.Lock()
	mmUserByID.UserByIDMock.callArgs = append(mmUserByID.UserByIDMock.callArgs, &mm_params)
	mmUserByID.UserByIDMock.mutex.Unlock()

	for _, e := range mmUserByID.UserByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmUserByID.UserByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUserByID.UserByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmUserByID.UserByIDMock.defaultExpectation.params
		mm_want_ptrs := mmUserByID.UserByIDMock.defaultExpectation.paramPtrs

		mm_got := UserMockUserByIDParams{ctx, userId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUserByID.t.Errorf("UserMock.UserByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUserByID.UserByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmUserByID.t.Errorf("UserMock.UserByID got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUserByID.UserByIDMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUserByID.t.Errorf("UserMock.UserByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUserByID.UserByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUserByID.UserByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmUserByID.t.Fatal("No results are set for the UserMock.UserByID")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmUserByID.funcUserByID != nil {
		return mmUserByID.funcUserByID(ctx, userId)
	}
	mmUserByID.t.Fatalf("Unexpected call to UserMock.UserByID. %v %v", ctx, userId)
	return
}

// UserByIDAfterCounter returns a count of finished UserMock.UserByID invocations
func (mmUserByID *UserMock) UserByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUserByID.afterUserByIDCounter)
}

// UserByIDBeforeCounter returns a count of UserMock.UserByID invocations
func (mmUserByID *UserMock) UserByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUserByID.beforeUserByIDCounter)
}

// Calls returns a list of arguments used in each call to UserMock.UserByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUserByID *mUserMockUserByID) Calls() []*UserMockUserByIDParams {
	mmUserByID.mutex.RLock()

	argCopy := make([]*UserMockUserByIDParams, len(mmUserByID.callArgs))
	copy(argCopy, mmUserByID.callArgs)

	mmUserByID.mutex.RUnlock()

	return argCopy
}

// MinimockUserByIDDone returns true if the count of the UserByID invocations corresponds
// the number of defined expectations
func (m *UserMock) MinimockUserByIDDone() bool {
	if m.UserByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UserByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UserByIDMock.invocationsDone()
}

// MinimockUserByIDInspect logs each unmet expectation
func (m *UserMock) MinimockUserByIDInspect() {
	for _, e := range m.UserByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserMock.UserByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUserByIDCounter := mm_atomic.LoadUint64(&m.afterUserByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UserByIDMock.defaultExpectation != nil && afterUserByIDCounter < 1 {
		if m.UserByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserMock.UserByID at\n%s", m.UserByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserMock.UserByID at\n%s with params: %#v", m.UserByIDMock.defaultExpectation.expectationOrigins.origin, *m.UserByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUserByID != nil && afterUserByIDCounter < 1 {
		m.t.Errorf("Expected call to UserMock.UserByID at\n%s", m.funcUserByIDOrigin)
	}

	if !m.UserByIDMock.invocationsDone() && afterUserByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to UserMock.UserByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UserByIDMock.expectedInvocations), m.UserByIDMock.expectedInvocationsOrigin, afterUserByIDCounter)
	}
}

type mUserMockValidateRole struct {
	optional           bool
	mock               *UserMock
	defaultExpectation *UserMockValidateRoleExpectation
	expectations       []*UserMockValidateRoleExpectation

	callArgs []*UserMockValidateRoleParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserMockValidateRoleExpectation specifies expectation struct of the RWUsers.ValidateRole
type UserMockValidateRoleExpectation struct {
	mock               *UserMock
	params             *UserMockValidateRoleParams
	paramPtrs          *UserMockValidateRoleParamPtrs
	expectationOrigins UserMockValidateRoleExpectationOrigins
	results            *UserMockValidateRoleResults
	returnOrigin       string
	Counter            uint64
}

// UserMockValidateRoleParams contains parameters of the RWUsers.ValidateRole
type UserMockValidateRoleParams struct {
	ctx  context.Context
	role string
}

// UserMockValidateRoleParamPtrs contains pointers to parameters of the RWUsers.ValidateRole
type UserMockValidateRoleParamPtrs struct {
	ctx  *context.Context
	role *string
}

// UserMockValidateRoleResults contains results of the RWUsers.ValidateRole
type UserMockValidateRoleResults struct {
	err error
}

// UserMockValidateRoleOrigins contains origins of expectations of the RWUsers.ValidateRole
type UserMockValidateRoleExpectationOrigins struct {
	origin     string
	originCtx  string
	originRole string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmValidateRole *mUserMockValidateRole) Optional() *mUserMockValidateRole {
	mmValidateRole.optional = true
	return mmValidateRole
}

// Expect sets up expected params for RWUsers.ValidateRole
func (mmValidateRole *mUserMockValidateRole) Expect(ctx context.Context, role string) *mUserMockValidateRole {
	if mmValidateRole.mock.funcValidateRole != nil {
		mmValidateRole.mock.t.Fatalf("UserMock.ValidateRole mock is already set by Set")
	}

	if mmValidateRole.defaultExpectation == nil {
		mmValidateRole.defaultExpectation = &UserMockValidateRoleExpectation{}
	}

	if mmValidateRole.defaultExpectation.paramPtrs != nil {
		mmValidateRole.mock.t.Fatalf("UserMock.ValidateRole mock is already set by ExpectParams functions")
	}

	mmValidateRole.defaultExpectation.params = &UserMockValidateRoleParams{ctx, role}
	mmValidateRole.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmValidateRole.expectations {
		if minimock.Equal(e.params, mmValidateRole.defaultExpectation.params) {
			mmValidateRole.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmValidateRole.defaultExpectation.params)
		}
	}

	return mmValidateRole
}

// ExpectCtxParam1 sets up expected param ctx for RWUsers.ValidateRole
func (mmValidateRole *mUserMockValidateRole) ExpectCtxParam1(ctx context.Context) *mUserMockValidateRole {
	if mmValidateRole.mock.funcValidateRole != nil {
		mmValidateRole.mock.t.Fatalf("UserMock.ValidateRole mock is already set by Set")
	}

	if mmValidateRole.defaultExpectation == nil {
		mmValidateRole.defaultExpectation = &UserMockValidateRoleExpectation{}
	}

	if mmValidateRole.defaultExpectation.params != nil {
		mmValidateRole.mock.t.Fatalf("UserMock.ValidateRole mock is already set by Expect")
	}

	if mmValidateRole.defaultExpectation.paramPtrs == nil {
		mmValidateRole.defaultExpectation.paramPtrs = &UserMockValidateRoleParamPtrs{}
	}
	mmValidateRole.defaultExpectation.paramPtrs.ctx = &ctx
	mmValidateRole.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmValidateRole
}

// ExpectRoleParam2 sets up expected param role for RWUsers.ValidateRole
func (mmValidateRole *mUserMockValidateRole) ExpectRoleParam2(role string) *mUserMockValidateRole {
	if mmValidateRole.mock.funcValidateRole != nil {
		mmValidateRole.mock.t.Fatalf("UserMock.ValidateRole mock is already set by Set")
	}

	if mmValidateRole.defaultExpectation == nil {
		mmValidateRole.defaultExpectation = &UserMockValidateRoleExpectation{}
	}

	if mmValidateRole.defaultExpectation.params != nil {
		mmValidateRole.mock.t.Fatalf("UserMock.ValidateRole mock is already set by Expect")
	}

	if mmValidateRole.defaultExpectation.paramPtrs == nil {
		mmValidateRole.defaultExpectation.paramPtrs = &UserMockValidateRoleParamPtrs{}
	}
	mmValidateRole.defaultExpectation.paramPtrs.role = &role
	mmValidateRole.defaultExpectation.expectationOrigins.originRole = minimock.CallerInfo(1)

	return mmValidateRole
}

// Inspect accepts an inspector function that has same arguments as the RWUsers.ValidateRole
func (mmValidateRole *mUserMockValidateRole) Inspect(f func(ctx context.Context, role string)) *mUserMockValidateRole {
	if mmValidateRole.mock.inspectFuncValidateRole != nil {
		mmValidateRole.mock.t.Fatalf("Inspect function is already set for UserMock.ValidateRole")
	}

	mmValidateRole.mock.inspectFuncValidateRole = f

	return mmValidateRole
}

// Return sets up results that will be returned by RWUsers.ValidateRole
func (mmValidateRole *mUserMockValidateRole) Return(err error) *UserMock {
	if mmValidateRole.mock.funcValidateRole != nil {
		mmValidateRole.mock.t.Fatalf("UserMock.ValidateRole mock is already set by Set")
	}

	if mmValidateRole.defaultExpectation == nil {
		mmValidateRole.defaultExpectation = &UserMockValidateRoleExpectation{mock: mmValidateRole.mock}
	}
	mmValidateRole.defaultExpectation.results = &UserMockValidateRoleResults{err}
	mmValidateRole.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmValidateRole.mock
}

// Set uses given function f to mock the RWUsers.ValidateRole method
func (mmValidateRole *mUserMockValidateRole) Set(f func(ctx context.Context, role string) (err error)) *UserMock {
	if mmValidateRole.defaultExpectation != nil {
		mmValidateRole.mock.t.Fatalf("Default expectation is already set for the RWUsers.ValidateRole method")
	}

	if len(mmValidateRole.expectations) > 0 {
		mmValidateRole.mock.t.Fatalf("Some expectations are already set for the RWUsers.ValidateRole method")
	}

	mmValidateRole.mock.funcValidateRole = f
	mmValidateRole.mock.funcValidateRoleOrigin = minimock.CallerInfo(1)
	return mmValidateRole.mock
}

// When sets expectation for the RWUsers.ValidateRole which will trigger the result defined by the following
// Then helper
func (mmValidateRole *mUserMockValidateRole) When(ctx context.Context, role string) *UserMockValidateRoleExpectation {
	if mmValidateRole.mock.funcValidateRole != nil {
		mmValidateRole.mock.t.Fatalf("UserMock.ValidateRole mock is already set by Set")
	}

	expectation := &UserMockValidateRoleExpectation{
		mock:               mmValidateRole.mock,
		params:             &UserMockValidateRoleParams{ctx, role},
		expectationOrigins: UserMockValidateRoleExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmValidateRole.expectations = append(mmValidateRole.expectations, expectation)
	return expectation
}

// Then sets up RWUsers.ValidateRole return parameters for the expectation previously defined by the When method
func (e *UserMockValidateRoleExpectation) Then(err error) *UserMock {
	e.results = &UserMockValidateRoleResults{err}
	return e.mock
}

// Times sets number of times RWUsers.ValidateRole should be invoked
func (mmValidateRole *mUserMockValidateRole) Times(n uint64) *mUserMockValidateRole {
	if n == 0 {
		mmValidateRole.mock.t.Fatalf("Times of UserMock.ValidateRole mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmValidateRole.expectedInvocations, n)
	mmValidateRole.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmValidateRole
}

func (mmValidateRole *mUserMockValidateRole) invocationsDone() bool {
	if len(mmValidateRole.expectations) == 0 && mmValidateRole.defaultExpectation == nil && mmValidateRole.mock.funcValidateRole == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmValidateRole.mock.afterValidateRoleCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmValidateRole.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ValidateRole implements mm_postgres.RWUsers
func (mmValidateRole *UserMock) ValidateRole(ctx context.Context, role string) (err error) {
	mm_atomic.AddUint64(&mmValidateRole.beforeValidateRoleCounter, 1)
	defer mm_atomic.AddUint64(&mmValidateRole.afterValidateRoleCounter, 1)

	mmValidateRole.t.Helper()

	if mmValidateRole.inspectFuncValidateRole != nil {
		mmValidateRole.inspectFuncValidateRole(ctx, role)
	}

	mm_params := UserMockValidateRoleParams{ctx, role}

	// Record call args
	mmValidateRole.ValidateRoleMock.mutex.Lock()
	mmValidateRole.ValidateRoleMock.callArgs = append(mmValidateRole.ValidateRoleMock.callArgs, &mm_params)
	mmValidateRole.ValidateRoleMock.mutex.Unlock()

	for _, e := range mmValidateRole.ValidateRoleMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmValidateRole.ValidateRoleMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmValidateRole.ValidateRoleMock.defaultExpectation.Counter, 1)
		mm_want := mmValidateRole.ValidateRoleMock.defaultExpectation.params
		mm_want_ptrs := mmValidateRole.ValidateRoleMock.defaultExpectation.paramPtrs

		mm_got := UserMockValidateRoleParams{ctx, role}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmValidateRole.t.Errorf("UserMock.ValidateRole got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmValidateRole.ValidateRoleMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.role != nil && !minimock.Equal(*mm_want_ptrs.role, mm_got.role) {
				mmValidateRole.t.Errorf("UserMock.ValidateRole got unexpected parameter role, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmValidateRole.ValidateRoleMock.defaultExpectation.expectationOrigins.originRole, *mm_want_ptrs.role, mm_got.role, minimock.Diff(*mm_want_ptrs.role, mm_got.role))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmValidateRole.t.Errorf("UserMock.ValidateRole got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmValidateRole.ValidateRoleMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmValidateRole.ValidateRoleMock.defaultExpectation.results
		if mm_results == nil {
			mmValidateRole.t.Fatal("No results are set for the UserMock.ValidateRole")
		}
		return (*mm_results).err
	}
	if mmValidateRole.funcValidateRole != nil {
		return mmValidateRole.funcValidateRole(ctx, role)
	}
	mmValidateRole.t.Fatalf("Unexpected call to UserMock.ValidateRole. %v %v", ctx, role)
	return
}

// ValidateRoleAfterCounter returns a count of finished UserMock.ValidateRole invocations
func (mmValidateRole *UserMock) ValidateRoleAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidateRole.afterValidateRoleCounter)
}

// ValidateRoleBeforeCounter returns a count of UserMock.ValidateRole invocations
func (mmValidateRole *UserMock) ValidateRoleBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidateRole.beforeValidateRoleCounter)
}

// Calls returns a list of arguments used in each call to UserMock.ValidateRole.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmValidateRole *mUserMockValidateRole) Calls() []*UserMockValidateRoleParams {
	mmValidateRole.mutex.RLock()

	argCopy := make([]*UserMockValidateRoleParams, len(mmValidateRole.callArgs))
	copy(argCopy, mmValidateRole.callArgs)

	mmValidateRole.mutex.RUnlock()

	return argCopy
}

// MinimockValidateRoleDone returns true if the count of the ValidateRole invocations corresponds
// the number of defined expectations
func (m *UserMock) MinimockValidateRoleDone() bool {
	if m.ValidateRoleMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ValidateRoleMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ValidateRoleMock.invocationsDone()
}

// MinimockValidateRoleInspect logs each unmet expectation
func (m *UserMock) MinimockValidateRoleInspect() {
	for _, e := range m.ValidateRoleMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserMock.ValidateRole at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterValidateRoleCounter := mm_atomic.LoadUint64(&m.afterValidateRoleCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ValidateRoleMock.defaultExpectation != nil && afterValidateRoleCounter < 1 {
		if m.ValidateRoleMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserMock.ValidateRole at\n%s", m.ValidateRoleMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserMock.ValidateRole at\n%s with params: %#v", m.ValidateRoleMock.defaultExpectation.expectationOrigins.origin, *m.ValidateRoleMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcValidateRole != nil && afterValidateRoleCounter < 1 {
		m.t.Errorf("Expected call to UserMock.ValidateRole at\n%s", m.funcValidateRoleOrigin)
	}

	if !m.ValidateRoleMock.invocationsDone() && afterValidateRoleCounter > 0 {
		m.t.Errorf("Expected %d calls to UserMock.ValidateRole at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ValidateRoleMock.expectedInvocations), m.ValidateRoleMock.expectedInvocationsOrigin, afterValidateRoleCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateUserInspect()

			m.MinimockUserByEmailInspect()

			m.MinimockUserByIDInspect()

			m.MinimockValidateRoleInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateUserDone() &&
		m.MinimockUserByEmailDone() &&
		m.MinimockUserByIDDone() &&
		m.MinimockValidateRoleDone()
}
